ADMIN_EXTENSION = r"""
<style>
#adminGate{position:fixed;inset:0;background:rgba(255,255,255,.96);z-index:200;display:none;place-items:center}
#adminGate.show{display:grid}.admin-login{width:min(430px,92vw);border:2px solid #111;background:#fff;padding:22px}.admin-login h2{font-size:16px;margin-bottom:14px}.admin-login input{width:100%;height:38px;border:1px solid #999;margin:5px 0 10px;padding:0 10px}.admin-login .warning{font-size:10px;line-height:1.45;border-left:3px solid #111;padding:8px 10px;margin:12px 0}
#adminButton{margin-left:12px}.admin-tab{display:none}.admin-tab.show{display:block}.admin-shell{max-width:1500px;margin-left:auto;margin-right:auto}.admin-hero{display:grid;grid-template-columns:repeat(5,1fr);border-left:1px solid #c7c7c7;border-top:1px solid #c7c7c7;margin:14px 0}.admin-hero>div{padding:12px;border-right:1px solid #c7c7c7;border-bottom:1px solid #c7c7c7;min-height:70px}.admin-hero strong{display:block;font-size:18px;margin-top:5px}.admin-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.admin-panel{border:1px solid #c7c7c7;padding:13px;min-width:0}.admin-targetbar{display:grid;grid-template-columns:minmax(240px,430px) auto auto;gap:8px}.admin-targetbar input{height:35px;border:1px solid #999;padding:0 10px;font:12px Consolas,monospace}.admin-output{border:1px solid #c7c7c7;min-height:190px;max-height:430px;overflow:auto;padding:12px;white-space:pre-wrap;font:10px/1.5 Consolas,monospace;background:#fff}.admin-row{padding:8px 0;border-bottom:1px solid #ddd;font-size:10px;line-height:1.5}.admin-row:last-child{border-bottom:0}.admin-badge{display:inline-block;border:1px solid #111;padding:3px 6px;font-size:9px;font-weight:700;margin-right:5px}.admin-danger{border-width:2px}.admin-toolbar{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.admin-table{max-height:470px}.admin-auth-label{font-size:9px;letter-spacing:.1em;margin-top:3px}.admin-default{font-weight:700}
@media(max-width:1000px){.admin-grid{grid-template-columns:1fr}.admin-hero{grid-template-columns:1fr 1fr}.admin-targetbar{grid-template-columns:1fr}}
</style>
<div id="adminGate">
  <div class="admin-login">
    <h2>Administrator Access</h2>
    <div class="label">Operator ID</div><input id="adminUser" autocomplete="username" value="admin">
    <div class="label">Password</div><input id="adminPass" type="password" autocomplete="current-password">
    <div class="warning">Administrator mode is local-console only. Remote access and containment are limited to explicitly enrolled endpoints and managed agents.</div>
    <div class="toolbar"><button class="btn" id="adminLoginBtn">Sign In</button><button class="btn" id="adminCancelBtn">Cancel</button></div>
    <div class="message" id="adminLoginMessage"></div>
  </div>
</div>
<script>
(()=>{
const A=id=>document.getElementById(id);
const ah=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let adminToken=sessionStorage.getItem('campusOpsAdminToken')||'',adminSelected='',adminInvestigation=null;
const adminPages={
  'admin-hunt':['Admin Hunt','Deep passive pivot across live evidence.'],
  'admin-forensics':['Forensics','IP-centered evidence and authorized private-lab probes.'],
  'admin-remote':['Remote Access','SSH/RDP only to explicitly enrolled systems.'],
  'admin-contain':['Containment','Agent-backed snapshot, isolation and restoration.']
};
function headers(){return adminToken?{'X-Campus-Admin':adminToken}:{}}
function jsonHeaders(){return {...headers(),'Content-Type':'application/json'}}
async function api(path,options={}){options.headers={...(options.headers||{}),...headers()};const r=await fetch(path,options),d=await r.json().catch(()=>({}));if(r.status===401){adminToken='';sessionStorage.removeItem('campusOpsAdminToken');hideAdmin();throw new Error('Administrator session expired. Sign in again.')}if(!r.ok)throw new Error(d.detail||`HTTP ${r.status}`);return d}
function ensureButton(){
  const header=document.querySelector('header .headstate');if(!header||A('adminButton'))return;
  const b=document.createElement('button');b.id='adminButton';b.className='btn';b.textContent=adminToken?'ADMIN · ON':'ADMIN';b.onclick=()=>adminToken?setView('admin-hunt'):showLogin();header.appendChild(b);
}
function showLogin(){A('adminGate')?.classList.add('show');setTimeout(()=>A('adminPass')?.focus(),30)}
function closeLogin(){A('adminGate')?.classList.remove('show');if(A('adminPass'))A('adminPass').value=''}
function injectAdminViews(){
  if(A('view-admin-hunt'))return;
  const nav=document.querySelector('nav'),main=document.querySelector('main'),foot=main?.querySelector('.foot');if(!nav||!main)return;
  Object.assign(pages,adminPages);
  const tabs=[['admin-hunt','Admin Hunt'],['admin-forensics','Forensics'],['admin-remote','Remote Access'],['admin-contain','Containment']];
  for(const [view,label] of tabs){const b=document.createElement('button');b.className='tab admin-tab';b.dataset.view=view;b.textContent=label;b.onclick=()=>setView(view);nav.appendChild(b)}
  const html=`
  <div class="view" id="view-admin-hunt"><section class="admin-shell"><div class="sectionhead"><div><h2>Administrator Hunt Workspace</h2><div class="small">Select one IP and pivot through current-session evidence without generating traffic.</div></div><button class="btn" data-admin-logout>Logout</button></div><div class="admin-targetbar"><input id="adminHuntTarget" placeholder="Target IP"><button class="btn" id="adminHuntRun">Hunt IP</button><button class="btn" id="adminHuntRefresh">Refresh Targets</button></div><div class="admin-hero" id="adminHuntStats"></div><div class="admin-grid"><div class="admin-panel"><div class="label">Assessment</div><div id="adminHuntAssessment"></div></div><div class="admin-panel"><div class="label">Top Evidence Pivots</div><div id="adminHuntPivots"></div></div></div><div class="admin-panel" style="margin-top:14px"><div class="label">Observed Targets</div><div class="tablewrap admin-table"><table><thead><tr><th>IP</th><th>Name</th><th>Class</th><th>Managed</th><th>Remote</th><th>Isolation</th><th>Actions</th></tr></thead><tbody id="adminTargetRows"></tbody></table></div></div></section></div>
  <div class="view" id="view-admin-forensics"><section class="admin-shell"><div class="sectionhead"><div><h2>Forensic Workbench</h2><div class="small">Passive correlation first; active probes require explicit confirmation and private lab scope.</div></div><button class="btn" data-admin-logout>Logout</button></div><div class="admin-targetbar"><input id="adminForensicTarget" placeholder="Target IP"><button class="btn" id="adminForensicPassive">Build Report</button><button class="btn admin-danger" id="adminForensicProbe">Authorized Probe</button></div><div class="admin-grid" style="margin-top:14px"><div class="admin-panel"><div class="label">Forensic Capability</div><div id="adminForensicTools"></div><div class="label" style="margin-top:14px">Related Evidence</div><div id="adminForensicEvidence"></div></div><div class="admin-panel"><div class="label">Probe Output</div><pre class="admin-output" id="adminForensicOutput">No active probe has been run.</pre></div></div></section></div>
  <div class="view" id="view-admin-remote"><section class="admin-shell"><div class="sectionhead"><div><h2>Remote Access Gateway</h2><div class="small">Launches only protocols explicitly enabled on enrolled endpoints.</div></div><button class="btn" data-admin-logout>Logout</button></div><div class="admin-panel"><div class="label">Enrolled Remote Systems</div><div class="tablewrap admin-table"><table><thead><tr><th>IP / Host</th><th>Name</th><th>SSH</th><th>RDP</th><th>Managed Agent</th><th>Actions</th></tr></thead><tbody id="adminRemoteRows"></tbody></table></div></div></section></div>
  <div class="view" id="view-admin-contain"><section class="admin-shell"><div class="sectionhead"><div><h2>Containment Console</h2><div class="small">Isolation is permitted only through an authenticated managed endpoint agent. Restore is always kept beside isolate.</div></div><button class="btn" data-admin-logout>Logout</button></div><div class="admin-targetbar"><input id="adminContainTarget" placeholder="Managed target IP"><button class="btn" id="adminContainInspect">Inspect</button><button class="btn" id="adminContainRefresh">Refresh</button></div><div class="admin-grid" style="margin-top:14px"><div class="admin-panel"><div class="label">Target State</div><div id="adminContainState"></div><div class="admin-toolbar"><button class="btn" id="adminSnapshot">Collect Snapshot</button><button class="btn admin-danger" id="adminIsolate">Isolate Host</button><button class="btn" id="adminRestore">Restore Network</button></div><div class="message" id="adminContainMessage"></div></div><div class="admin-panel"><div class="label">Control Rules</div><div class="admin-row">Containment requires a mapped managed agent.</div><div class="admin-row">Isolation preserves the Campus Ops management address.</div><div class="admin-row">SSH/RDP is separate and requires explicit remote-console enrollment.</div><div class="admin-row">Passive observations alone never authorize endpoint control.</div></div></div><div class="admin-panel" style="margin-top:14px"><div class="label">Managed Targets</div><div id="adminManagedRows"></div></div></section></div>`;
  const holder=document.createElement('div');holder.innerHTML=html;while(holder.firstChild)main.insertBefore(holder.firstChild,foot||null);
  wireAdmin();
}
function showAdmin(){injectAdminViews();document.querySelectorAll('.admin-tab').forEach(x=>x.classList.add('show'));const b=A('adminButton');if(b)b.textContent='ADMIN · ON';loadTargets()}
function hideAdmin(){document.querySelectorAll('.admin-tab').forEach(x=>x.classList.remove('show'));const b=A('adminButton');if(b)b.textContent='ADMIN';if(document.querySelector('.tab.active')?.dataset?.view?.startsWith('admin-'))setView('overview')}
async function login(){const m=A('adminLoginMessage');m.textContent='Signing in...';try{const r=await fetch('/api/v1/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:A('adminUser').value,password:A('adminPass').value})}),d=await r.json();if(!r.ok)throw new Error(d.detail||'Login failed');adminToken=d.token;sessionStorage.setItem('campusOpsAdminToken',adminToken);closeLogin();showAdmin();m.textContent='';if(d.default_password){const sm=A('footerStatus');if(sm)sm.textContent='ADMIN ACTIVE · DEFAULT LAB PASSWORD IN USE';}}catch(e){m.textContent=e.message}}
async function logout(){try{await api('/api/v1/admin/logout',{method:'POST'})}catch{}adminToken='';sessionStorage.removeItem('campusOpsAdminToken');hideAdmin()}
function syncTarget(value){adminSelected=value||adminSelected;for(const id of ['adminHuntTarget','adminForensicTarget','adminContainTarget']){const el=A(id);if(el&&adminSelected)el.value=adminSelected}}
async function loadTargets(){if(!adminToken)return;try{const d=await api('/api/v1/admin/targets'),rows=d.targets||[];const table=A('adminTargetRows');if(table)table.innerHTML=rows.map(x=>`<tr><td class="mono">${ah(x.ip)}</td><td>${ah(x.name||'—')}</td><td>${ah(x.classification)}</td><td>${x.managed?'YES':'NO'}</td><td>${x.remote_enrolled?'YES':'NO'}</td><td>${ah(x.isolation_state||'—')}</td><td><div class="toolbar"><button class="btn" data-admin-hunt="${ah(x.ip)}">Hunt</button>${x.remote_enrolled?`<button class="btn" data-admin-remote="${ah(x.ip)}">Access</button>`:''}${x.managed?`<button class="btn" data-admin-contain="${ah(x.ip)}">Control</button>`:''}</div></td></tr>`).join('')||'<tr><td colspan="7" class="muted">No observed targets</td></tr>';const rem=A('adminRemoteRows');if(rem)rem.innerHTML=rows.filter(x=>x.remote_enrolled).map(x=>`<tr><td class="mono">${ah(x.ip)}</td><td>${ah(x.name||'—')}</td><td>${x.allow_ssh?'YES':'NO'}</td><td>${x.allow_rdp?'YES':'NO'}</td><td>${x.managed?'YES':'NO'}</td><td><div class="toolbar">${x.allow_ssh?`<button class="btn" data-connect-ssh="${ah(x.ip)}">SSH</button>`:''}${x.allow_rdp?`<button class="btn" data-connect-rdp="${ah(x.ip)}">RDP</button>`:''}<button class="btn" data-admin-hunt="${ah(x.ip)}">Hunt</button></div></td></tr>`).join('')||'<tr><td colspan="6" class="muted">No explicitly enrolled remote systems</td></tr>';const managed=A('adminManagedRows');if(managed)managed.innerHTML=rows.filter(x=>x.managed).map(x=>`<div class="admin-row"><b class="mono">${ah(x.ip)}</b> · ${ah(x.name||x.agent_id||'managed endpoint')} · ${ah(x.agent_status||'UNKNOWN')} · ${ah(x.isolation_state||'UNKNOWN')} <button class="btn" data-admin-contain="${ah(x.ip)}">Inspect</button></div>`).join('')||'<div class="muted">No managed agents mapped to observed IPs.</div>';wireDynamic();}catch(e){const t=A('adminTargetRows');if(t)t.innerHTML=`<tr><td colspan="7">${ah(e.message)}</td></tr>`}}
function wireDynamic(){document.querySelectorAll('[data-admin-hunt]').forEach(b=>b.onclick=()=>{syncTarget(b.dataset.adminHunt);setView('admin-hunt');runHunt()});document.querySelectorAll('[data-admin-remote]').forEach(b=>b.onclick=()=>{syncTarget(b.dataset.adminRemote);setView('admin-remote')});document.querySelectorAll('[data-admin-contain]').forEach(b=>b.onclick=()=>{syncTarget(b.dataset.adminContain);setView('admin-contain');inspectContain()});document.querySelectorAll('[data-connect-ssh]').forEach(b=>b.onclick=()=>connectTarget(b.dataset.connectSsh,'ssh'));document.querySelectorAll('[data-connect-rdp]').forEach(b=>b.onclick=()=>connectTarget(b.dataset.connectRdp,'rdp'))}
function renderInvestigation(d){adminInvestigation=d;const s=d.summary||{},r=d.risk||{},a=d.asset||{},agent=d.managed_agent||{};const hero=A('adminHuntStats');if(hero)hero.innerHTML=[['Risk',`${r.score||0}/100`],['Assessment',r.assessment||'—'],['Flows',s.flow_count||0],['Peers',s.peer_count||0],['Open Incidents',s.open_incident_count||0]].map(x=>`<div><div class="label">${ah(x[0])}</div><strong>${ah(x[1])}</strong></div>`).join('');const ass=A('adminHuntAssessment');if(ass)ass.innerHTML=`<div class="admin-row"><b class="mono">${ah(d.target)}</b> · ${ah(a.classification||a.role||'Observed peer')}</div><div class="admin-row">Managed agent: ${d.manageable?ah(agent.endpoint_id||'YES'):'NO'}</div><div class="admin-row">Observed packets: ${ah(s.packets||0)} · Alerts: ${ah(s.alert_count||0)} · Incidents: ${ah(s.incident_count||0)}</div>${(r.reasons||[]).map(x=>`<div class="admin-row">${ah(x)}</div>`).join('')}`;const piv=A('adminHuntPivots');if(piv)piv.innerHTML=[...(s.top_peers||[]).map(x=>`<div class="admin-row"><b>Peer</b> · <span class="mono">${ah(x[0])}</span> · ${ah(x[1])} packets</div>`),...(s.top_services||[]).map(x=>`<div class="admin-row"><b>Service</b> · ${ah(x[0])} · ${ah(x[1])}</div>`),...(s.top_applications||[]).map(x=>`<div class="admin-row"><b>Application</b> · ${ah(x[0])} · ${ah(x[1])}</div>`)].slice(0,24).join('')||'<div class="muted">No current pivots.</div>';const tools=A('adminForensicTools');if(tools)tools.innerHTML=Object.entries(d.forensic_tools||{}).map(([k,v])=>`<span class="admin-badge">${ah(k.toUpperCase())} · ${v?'READY':'MISSING'}</span>`).join('');const ev=A('adminForensicEvidence');if(ev)ev.innerHTML=`<div class="admin-row">${ah(s.flow_count||0)} live flows · ${ah(s.alert_count||0)} alerts · ${ah(s.incident_count||0)} incidents</div>${(d.incidents||[]).slice(0,8).map(i=>`<div class="admin-row"><b>${ah(i.severity)} · ${ah(i.title)}</b><br>${ah(i.status||'OPEN')} · ${ah(i.source||'')}</div>`).join('')}`;syncTarget(d.target)}
async function runHunt(){const target=(A('adminHuntTarget')?.value||adminSelected).trim();if(!target)return;syncTarget(target);try{renderInvestigation(await api(`/api/v1/admin/forensics/${encodeURIComponent(target)}`))}catch(e){const a=A('adminHuntAssessment');if(a)a.textContent=e.message}}
async function runForensic(){const target=(A('adminForensicTarget')?.value||adminSelected).trim();if(!target)return;syncTarget(target);try{renderInvestigation(await api(`/api/v1/admin/forensics/${encodeURIComponent(target)}`));A('adminForensicOutput').textContent='Passive evidence report built. Active probe has not been run.'}catch(e){A('adminForensicOutput').textContent=e.message}}
async function probeForensic(){const target=(A('adminForensicTarget')?.value||adminSelected).trim();if(!target)return;if(!confirm(`Run authorized private-lab probe against ${target}? This generates network traffic.`))return;const out=A('adminForensicOutput');out.textContent='Running authorized probe...';try{const d=await api(`/api/v1/admin/forensics/${encodeURIComponent(target)}/probe`,{method:'POST',headers:jsonHeaders(),body:JSON.stringify({authorized:true,include_services:true})});out.textContent=Object.entries(d.results||{}).map(([k,v])=>`=== ${k.toUpperCase()} · ${v.status||'UNKNOWN'} ===\n${v.output||''}`).join('\n\n')||'No probe results.'}catch(e){out.textContent=`ERROR: ${e.message}`}}
async function connectTarget(target,protocol){try{const d=await api(`/api/v1/admin/targets/${encodeURIComponent(target)}/connect`,{method:'POST',headers:jsonHeaders(),body:JSON.stringify({protocol})});alert(`${protocol.toUpperCase()} ${d.status||'REQUESTED'} for ${target}`)}catch(e){alert(e.message)}}
async function inspectContain(){const target=(A('adminContainTarget')?.value||adminSelected).trim();if(!target)return;syncTarget(target);try{const d=await api(`/api/v1/admin/forensics/${encodeURIComponent(target)}`);renderInvestigation(d);const a=d.managed_agent||{},el=A('adminContainState');el.innerHTML=`<div class="admin-row"><b class="mono">${ah(d.target)}</b></div><div class="admin-row">Managed: ${d.manageable?'YES':'NO'}</div><div class="admin-row">Agent: ${ah(a.endpoint_id||'—')} · ${ah(a.status||'—')}</div><div class="admin-row">Isolation: ${ah((a.telemetry||{}).isolation_state||'UNKNOWN')}</div><div class="admin-row">Risk: ${ah((d.risk||{}).score||0)}/100 · ${ah((d.risk||{}).assessment||'—')}</div>`;for(const id of ['adminSnapshot','adminIsolate','adminRestore'])A(id).disabled=!d.manageable}catch(e){A('adminContainState').textContent=e.message}}
async function containAction(action){const target=(A('adminContainTarget')?.value||adminSelected).trim();if(!target)return;if(action==='isolate'&&!confirm(`Isolate managed host ${target}? Restore remains available from this console.`))return;const m=A('adminContainMessage');m.textContent=`Queuing ${action}...`;try{const d=await api(`/api/v1/admin/targets/${encodeURIComponent(target)}/${action}`,{method:'POST'});m.textContent=`${action.toUpperCase()} queued · ${d.job?.job_id||'job created'}`;setTimeout(inspectContain,1600)}catch(e){m.textContent=e.message}}
function wireAdmin(){A('adminHuntRun').onclick=runHunt;A('adminHuntRefresh').onclick=loadTargets;A('adminForensicPassive').onclick=runForensic;A('adminForensicProbe').onclick=probeForensic;A('adminContainInspect').onclick=inspectContain;A('adminContainRefresh').onclick=loadTargets;A('adminSnapshot').onclick=()=>containAction('snapshot');A('adminIsolate').onclick=()=>containAction('isolate');A('adminRestore').onclick=()=>containAction('restore');document.querySelectorAll('[data-admin-logout]').forEach(b=>b.onclick=logout);for(const id of ['adminHuntTarget','adminForensicTarget','adminContainTarget'])A(id)?.addEventListener('keydown',e=>{if(e.key==='Enter'){adminSelected=e.target.value.trim();if(id==='adminHuntTarget')runHunt();else if(id==='adminForensicTarget')runForensic();else inspectContain()}})}
async function restoreSession(){if(!adminToken)return;try{const d=await api('/api/v1/admin/status');if(d.authenticated)showAdmin();else{adminToken='';sessionStorage.removeItem('campusOpsAdminToken')}}catch{adminToken='';sessionStorage.removeItem('campusOpsAdminToken')}}
setTimeout(()=>{ensureButton();injectAdminViews();A('adminLoginBtn').onclick=login;A('adminCancelBtn').onclick=closeLogin;A('adminPass').addEventListener('keydown',e=>{if(e.key==='Enter')login()});restoreSession()},100);
})();
</script>
"""
