ADMIN_DEEP_EXTENSION = r"""
<style>
.admin-deep-tab{display:none}.admin-deep-tab.show{display:block}.deep-shell{max-width:1500px;margin:0 auto}.deep-bar{display:grid;grid-template-columns:minmax(240px,420px) auto auto auto;gap:8px}.deep-bar input{height:35px;border:1px solid #999;padding:0 10px;font:12px Consolas,monospace}.deep-stats{display:grid;grid-template-columns:repeat(6,1fr);border-left:1px solid #c7c7c7;border-top:1px solid #c7c7c7;margin:14px 0}.deep-stat{padding:11px;border-right:1px solid #c7c7c7;border-bottom:1px solid #c7c7c7;min-height:72px}.deep-stat strong{display:block;font-size:18px;margin-top:5px}.deep-grid{display:grid;grid-template-columns:1.15fr .85fr;gap:14px}.deep-panel{border:1px solid #c7c7c7;padding:12px;min-width:0}.deep-list{max-height:330px;overflow:auto}.deep-row{padding:7px 0;border-bottom:1px solid #ddd;font-size:10px;line-height:1.45}.deep-row:last-child{border-bottom:0}.deep-table{max-height:430px}.deep-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.deep-output{white-space:pre-wrap;font:10px/1.45 Consolas,monospace;max-height:280px;overflow:auto;border:1px solid #ddd;padding:10px;min-height:90px}
@media(max-width:1000px){.deep-grid{grid-template-columns:1fr}.deep-stats{grid-template-columns:1fr 1fr 1fr}.deep-bar{grid-template-columns:1fr 1fr}}
</style>
<script>
(()=>{
const D=id=>document.getElementById(id);
const de=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let deepTarget='',deepData=null;
function token(){return sessionStorage.getItem('campusOpsAdminToken')||''}
function headers(json=false){const h={'X-Campus-Admin':token()};if(json)h['Content-Type']='application/json';return h}
async function api(path,options={}){options.headers={...(options.headers||{}),...headers(false)};const r=await fetch(path,options),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||`HTTP ${r.status}`);return d}
function inject(){
 if(D('view-admin-deep'))return;
 const nav=document.querySelector('nav'),main=document.querySelector('main'),foot=main?.querySelector('.foot');if(!nav||!main)return;
 try{pages['admin-deep']=['Endpoint Deep','Managed endpoint process, connection, service and containment detail.']}catch{}
 const b=document.createElement('button');b.className='tab admin-deep-tab';b.dataset.view='admin-deep';b.textContent='Endpoint Deep';b.onclick=()=>setView('admin-deep');nav.appendChild(b);
 const v=document.createElement('div');v.className='view';v.id='view-admin-deep';v.innerHTML=`<section class="deep-shell"><div class="sectionhead"><div><h2>Endpoint Deep-Dive</h2><div class="small">Correlates authenticated endpoint telemetry with network evidence. Control actions require a managed agent.</div></div></div><div class="deep-bar"><input id="deepTarget" placeholder="Managed target IP"><button class="btn" id="deepLoad">Load Dossier</button><button class="btn" id="deepSnapshot">Collect Snapshot</button><button class="btn" id="deepContain">Open Containment</button></div><div class="message" id="deepMessage" style="margin-top:8px"></div><div class="deep-stats" id="deepStats"></div><div class="deep-grid"><div class="deep-panel"><div class="sectionhead"><h2>Networked Processes</h2><div class="note">PID-to-connection correlation from authenticated agent telemetry.</div></div><div class="tablewrap deep-table"><table><thead><tr><th>PID</th><th>Process</th><th>User</th><th>Peers</th><th>Public</th><th>Admin</th><th>Listeners</th><th>Action</th></tr></thead><tbody id="deepProcessRows"></tbody></table></div></div><div class="deep-panel"><div class="label">Behavior Findings</div><div class="deep-list" id="deepFindings"></div><div class="label" style="margin-top:12px">Users</div><div id="deepUsers" class="deep-row"></div></div></div><div class="deep-grid" style="margin-top:14px"><div class="deep-panel"><div class="sectionhead"><h2>Remote Connections</h2></div><div class="tablewrap deep-table"><table><thead><tr><th>Process</th><th>PID</th><th>Remote</th><th>Status</th><th>Action</th></tr></thead><tbody id="deepConnectionRows"></tbody></table></div></div><div class="deep-panel"><div class="sectionhead"><h2>Listening Services</h2></div><div class="deep-list" id="deepListeners"></div><div class="label" style="margin-top:12px">Running Services</div><div class="deep-list" id="deepServices"></div></div></div><div class="deep-panel" style="margin-top:14px"><div class="sectionhead"><h2>Network Security Correlation</h2></div><div id="deepNetworkEvidence" class="deep-list"></div></div><div class="deep-panel" style="margin-top:14px"><div class="label">File Quarantine</div><div class="deep-actions"><input id="deepFilePath" placeholder="Full path on managed endpoint" style="min-width:420px;height:34px;border:1px solid #999;padding:0 9px"><button class="btn" id="deepQuarantine">Queue Quarantine</button></div><div class="small">The file is moved only by the authenticated endpoint agent. No file is touched from passive network evidence.</div></div></section>`;main.insertBefore(v,foot||null);wire();
}
function visible(){const b=document.querySelector('.admin-deep-tab');if(!b)return;b.classList.toggle('show',!!token())}
function setTarget(value){deepTarget=String(value||'').trim();if(D('deepTarget'))D('deepTarget').value=deepTarget}
function render(d){
 deepData=d;setTarget(d.target);const e=d.endpoint||{},r=d.risk||{},s=d.summary||{},controls=d.controls||{};
 D('deepStats').innerHTML=[['Managed',d.managed?'YES':'NO'],['Risk',`${r.score||0}/100`],['Processes',e.process_count||0],['Connections',e.remote_connection_count||0],['Listeners',e.listener_count||0],['Open Incidents',s.open_incident_count||0]].map(x=>`<div class="deep-stat"><div class="label">${de(x[0])}</div><strong>${de(x[1])}</strong></div>`).join('');
 const procs=d.processes||[];D('deepProcessRows').innerHTML=procs.map(p=>`<tr><td class="mono">${de(p.pid)}</td><td>${de(p.name||'—')}</td><td>${de(p.user||'—')}</td><td>${de(p.unique_remote_peers||p.peer_count||0)}</td><td>${de(p.public_peer_count||0)}</td><td>${de(p.admin_peer_count||0)}</td><td>${de((p.listening_ports||[]).join(', ')||'—')}</td><td>${controls.can_stop_process?`<button class="btn" data-stop-pid="${de(p.pid)}">Stop</button>`:'—'}</td></tr>`).join('')||'<tr><td colspan="8" class="muted">No endpoint process telemetry.</td></tr>';
 D('deepFindings').innerHTML=(d.findings||[]).map(f=>`<div class="deep-row"><b>${de(f.severity||'')} · ${de(f.type||'Finding')}</b><br>${de(f.detail||'')}</div>`).join('')||'<div class="muted">No current endpoint behavior findings.</div>';
 D('deepUsers').textContent=(d.users||[]).join(' · ')||'No logged-on users reported.';
 D('deepConnectionRows').innerHTML=(d.connections||[]).slice(0,250).map(c=>`<tr><td>${de(c.process||'—')}</td><td class="mono">${de(c.pid||'—')}</td><td class="mono">${de(c.remote||'—')}</td><td>${de(c.status||'—')}</td><td>${controls.can_block_peer&&c.remote_ip?`<button class="btn" data-block-peer="${de(c.remote_ip)}">Block Peer</button>`:'—'}</td></tr>`).join('')||'<tr><td colspan="5" class="muted">No active remote connections.</td></tr>';
 D('deepListeners').innerHTML=(d.listeners||[]).map(x=>`<div class="deep-row"><b>${de(x.port)}</b> · ${de(x.process||'unknown process')} · PID ${de(x.pid||'—')} ${x.administrative_port?'· ADMIN SERVICE':''}</div>`).join('')||'<div class="muted">No listening socket telemetry.</div>';
 D('deepServices').innerHTML=(d.services||[]).slice(0,80).map(x=>`<div class="deep-row"><b>${de(x.name||x.display_name||'service')}</b> · ${de(x.status||'')}</div>`).join('')||'<div class="muted">No service telemetry.</div>';
 const n=d.network||{},items=[...(n.incidents||[]).slice(0,10).map(i=>`<div class="deep-row"><b>${de(i.severity||'')} · ${de(i.title||'Incident')}</b><br>${de(i.status||'OPEN')} · ${de(i.source||'')}</div>`),...(n.alerts||[]).slice(0,10).map(a=>`<div class="deep-row"><b>${de(a.severity||'')} · ${de((a.payload||{}).title||'Alert')}</b></div>`)];D('deepNetworkEvidence').innerHTML=items.join('')||'<div class="muted">No current incident or alert correlation for this endpoint.</div>';
 D('deepSnapshot').disabled=!controls.can_collect_snapshot;D('deepQuarantine').disabled=!controls.can_quarantine_file;document.querySelectorAll('[data-stop-pid]').forEach(b=>b.onclick=()=>stopProcess(Number(b.dataset.stopPid)));document.querySelectorAll('[data-block-peer]').forEach(b=>b.onclick=()=>blockPeer(b.dataset.blockPeer));
}
async function load(){const t=(D('deepTarget')?.value||deepTarget).trim();if(!t)return;setTarget(t);D('deepMessage').textContent='Loading endpoint dossier...';try{const d=await api(`/api/v1/admin/deep/${encodeURIComponent(t)}`);render(d);D('deepMessage').textContent=d.managed?'Managed endpoint dossier loaded.':'Passive network dossier loaded. Enroll the endpoint agent for process-level control.';}catch(e){D('deepMessage').textContent=e.message}}
async function snapshot(){if(!deepTarget)return;try{const d=await api(`/api/v1/admin/deep/${encodeURIComponent(deepTarget)}/snapshot`,{method:'POST'});D('deepMessage').textContent=`Snapshot queued · ${d.job?.job_id||'job created'}`;}catch(e){D('deepMessage').textContent=e.message}}
async function stopProcess(pid){if(!deepTarget||!pid)return;if(!confirm(`Stop PID ${pid} on managed host ${deepTarget}?`))return;try{const r=await fetch(`/api/v1/admin/deep/${encodeURIComponent(deepTarget)}/terminate`,{method:'POST',headers:headers(true),body:JSON.stringify({pid})}),d=await r.json();if(!r.ok)throw new Error(d.detail||'Stop failed');D('deepMessage').textContent=`Stop process queued · ${d.job?.job_id||''}`;}catch(e){D('deepMessage').textContent=e.message}}
async function blockPeer(ip){if(!deepTarget||!ip)return;if(!confirm(`Block ${ip} on managed host ${deepTarget}?`))return;try{const r=await fetch(`/api/v1/admin/deep/${encodeURIComponent(deepTarget)}/block-peer`,{method:'POST',headers:headers(true),body:JSON.stringify({remote_ip:ip})}),d=await r.json();if(!r.ok)throw new Error(d.detail||'Block failed');D('deepMessage').textContent=`Block peer queued · ${d.job?.job_id||''}`;}catch(e){D('deepMessage').textContent=e.message}}
async function quarantine(){const path=(D('deepFilePath')?.value||'').trim();if(!deepTarget||!path)return;if(!confirm(`Queue quarantine for ${path} on ${deepTarget}?`))return;try{const r=await fetch(`/api/v1/admin/deep/${encodeURIComponent(deepTarget)}/quarantine`,{method:'POST',headers:headers(true),body:JSON.stringify({path})}),d=await r.json();if(!r.ok)throw new Error(d.detail||'Quarantine failed');D('deepMessage').textContent=`Quarantine queued · ${d.job?.job_id||''}`;}catch(e){D('deepMessage').textContent=e.message}}
function wire(){D('deepLoad').onclick=load;D('deepSnapshot').onclick=snapshot;D('deepQuarantine').onclick=quarantine;D('deepContain').onclick=()=>{if(deepTarget){const x=document.getElementById('adminContainTarget');if(x)x.value=deepTarget;try{setView('admin-contain')}catch{}}};D('deepTarget').addEventListener('keydown',e=>{if(e.key==='Enter')load()})}
inject();visible();setInterval(visible,700);window.campusOpsOpenDeepTarget=target=>{inject();visible();setTarget(target);try{setView('admin-deep')}catch{}load()};
})();
</script>
"""
