AUTONOMY_UI_EXTENSION = r"""
<style>
#autonomyPanel{margin-top:16px}.autonomy-grid{display:grid;grid-template-columns:repeat(4,1fr);border-left:1px solid #c7c7c7;border-top:1px solid #c7c7c7}.autonomy-grid>div{padding:12px;border-right:1px solid #c7c7c7;border-bottom:1px solid #c7c7c7}.autonomy-grid strong{display:block;font-size:18px;margin-top:5px}.autonomy-row{display:grid;grid-template-columns:minmax(130px,1fr) 80px 100px 120px 120px;gap:8px;padding:9px 0;border-bottom:1px solid #ddd;font-size:10px;align-items:center}.autonomy-row b{font-size:11px}.autonomy-policy{border:1px solid #c7c7c7;padding:12px;margin-top:12px;font-size:10px;line-height:1.55}
@media(max-width:900px){.autonomy-grid{grid-template-columns:1fr 1fr}.autonomy-row{grid-template-columns:1fr 70px 100px}.autonomy-row span:nth-child(n+4){grid-column:1/-1}}
</style>
<script>
(()=>{
const $=id=>document.getElementById(id);
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function target(){return $('view-admin-command')||$('view-system')}
function install(){const host=target();if(!host||$('autonomyPanel'))return;const s=document.createElement('section');s.id='autonomyPanel';s.innerHTML=`<div class="sectionhead"><div><h2>Governed Autonomy</h2><div class="small">Closed-loop response decisioning with evidence, confidence and control gates.</div></div><button class="btn" id="autonomyRefresh">Refresh</button></div><div class="autonomy-grid" id="autonomySummary"></div><div class="panel" style="margin-top:12px"><div class="label">Response Candidates</div><div id="autonomyRows" style="margin-top:8px"></div></div><div class="autonomy-policy" id="autonomyPolicy"></div>`;host.appendChild(s);$('autonomyRefresh').onclick=load;load()}
async function load(){if(!$('autonomyPanel'))return;try{const r=await fetch('/api/v1/system/autonomy',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error('HTTP '+r.status);const decisions=d.decisions||[],eligible=decisions.filter(x=>x.automation_gate==='ELIGIBLE').length;$('autonomySummary').innerHTML=[['Mode',d.mode||'—'],['Candidates',d.decision_count||0],['Isolation eligible',eligible],['Auto containment',d.automatic_containment_enabled?'ENABLED':'OFF']].map(x=>`<div><div class="label">${esc(x[0])}</div><strong>${esc(x[1])}</strong></div>`).join('');$('autonomyRows').innerHTML=decisions.slice(0,20).map(x=>`<div class="autonomy-row"><b class="mono">${esc(x.target)}</b><span>${esc(x.risk_score)}</span><span>${esc(x.recommendation)}</span><span>${esc(x.automation_gate)}</span><span>${esc(x.independent_sources)} sources</span></div>`).join('')||'<div class="muted">No response candidates in the current session.</div>';const p=d.policy||{};$('autonomyPolicy').innerHTML=`<b>Policy:</b> isolate only at risk ≥ ${esc(p.isolation_threshold)} with ≥ ${esc(p.minimum_independent_sources)} independent evidence sources and ≥ ${esc(p.minimum_high_confidence_events)} high-confidence events. Managed endpoint control is mandatory. Automatic rule promotion is disabled and rollback is required.`}catch(e){$('autonomyRows').textContent='Autonomy engine unavailable: '+e.message}}
setTimeout(install,900);setInterval(()=>{install();if($('autonomyPanel'))load()},5000);
})();
</script>
"""
