CONSOLE_CLEANUP_EXTENSION = r"""
<style>
nav{overflow-x:hidden!important;flex-wrap:nowrap!important}.tab.console-secondary{display:none!important}
.console-shortcuts{display:flex;gap:6px;flex-wrap:wrap;align-items:center;margin:8px 0 0}.console-shortcuts .btn{padding:6px 9px}
#engineReadinessCompact{margin-top:16px}.engine-grid{display:grid;grid-template-columns:repeat(4,minmax(150px,1fr));border-left:1px solid #c7c7c7;border-top:1px solid #c7c7c7}.engine-cell{padding:11px;border-right:1px solid #c7c7c7;border-bottom:1px solid #c7c7c7;min-height:76px}.engine-cell strong{display:block;font-size:16px;margin-top:5px}
.red-live-grid{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(300px,.5fr);gap:12px}.red-live-stage{height:560px;border:1px solid #555;background:#050505;position:relative;overflow:hidden}.red-live-stage svg{width:100%;height:100%;display:block}.red-live-hud{position:absolute;left:12px;top:12px;border:1px solid #777;background:#0b0b0be8;padding:10px 12px;font:10px Consolas,monospace;line-height:1.5;z-index:2}.red-live-side{border:1px solid #555;background:#0f0f0f;padding:12px}.red-live-stat{display:grid;grid-template-columns:1fr 1fr;border-top:1px solid #444;border-left:1px solid #444;margin:8px 0}.red-live-stat>div{padding:9px;border-right:1px solid #444;border-bottom:1px solid #444}.red-control-row{display:grid;grid-template-columns:1fr auto;gap:8px;padding:10px 0;border-bottom:1px solid #333}.red-control-row:last-child{border-bottom:0}.red-control-row b{display:block}.red-control-row span{color:#aaa;font-size:10px}.red-control-danger{border:2px solid #fff!important;font-weight:800!important}.red-timebar{height:38px;border:1px solid #555;margin-top:10px;position:relative;background:#090909}.red-timebar span{position:absolute;bottom:0;width:3px;background:#fff}.red-live-event{padding:7px 0;border-bottom:1px solid #2d2d2d;font-size:10px}.red-live-event:last-child{border-bottom:0}.red-pulse{fill:#fff;opacity:.8}.red-trail{stroke:#777;stroke-width:1}.red-live-node{fill:#0a0a0a;stroke:#fff;stroke-width:1.4}.red-live-target{fill:#fff;stroke:#fff;stroke-width:2}.red-live-label{fill:#fff;font:9px Consolas,monospace}.red-live-target-label{fill:#000;font:700 9px Consolas,monospace}
.purple-score{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid #555;border-left:1px solid #555;margin-bottom:12px}.purple-score>div{padding:14px;border-right:1px solid #555;border-bottom:1px solid #555;background:#0e0e0e}.purple-score strong{display:block;font-size:28px;margin-top:5px}.purple-table{width:100%;border-collapse:collapse;font-size:10px}.purple-table th,.purple-table td{border:1px solid #3b3b3b;padding:9px;text-align:left;vertical-align:top}.purple-table th{background:#111;letter-spacing:.08em}.purple-gap-high{font-weight:800;text-decoration:underline}.purple-exercise{display:grid;grid-template-columns:34px 1fr;gap:10px;padding:10px 0;border-bottom:1px solid #333}.purple-exercise:last-child{border-bottom:0}.purple-num{width:28px;height:28px;border:1px solid #aaa;display:grid;place-items:center;font-weight:700}
@media(max-width:1050px){.engine-grid{grid-template-columns:repeat(2,1fr)}.red-live-grid{grid-template-columns:1fr}.red-live-stage{height:430px}.purple-score{grid-template-columns:1fr}}@media(max-width:650px){.engine-grid{grid-template-columns:1fr}}
</style>
<script>
(()=>{
const CORE=['overview','network','topology','pathspace','assets','security','system'];
const SECONDARY=['traffic','endpoints','response','evidence','history'];
const LABELS={overview:'Overview',network:'Network',topology:'Topology',pathspace:'Path Space',assets:'Assets',security:'Security',system:'System'};
const $=id=>document.getElementById(id);
function go(view){if(typeof window.setView==='function')window.setView(view);else document.querySelector(`button.tab[data-view="${view}"]`)?.click()}
function compactPrimaryNav(){const nav=document.querySelector('nav');if(!nav)return;for(const view of SECONDARY){nav.querySelector(`button.tab[data-view="${view}"]`)?.classList.add('console-secondary')}for(const view of CORE){const b=nav.querySelector(`button.tab[data-view="${view}"]`);if(b)b.textContent=LABELS[view]}}
function shortcuts(container,items){if(!container||container.querySelector('.console-shortcuts'))return;const row=document.createElement('div');row.className='console-shortcuts';for(const [label,view] of items){const b=document.createElement('button');b.className='btn';b.textContent=label;b.onclick=()=>go(view);row.appendChild(b)}container.insertBefore(row,container.firstChild)}
function installShortcuts(){shortcuts($('view-network'),[['Live Traffic','traffic']]);shortcuts($('view-assets'),[['Endpoint Telemetry','endpoints']]);shortcuts($('view-security'),[['Response','response'],['Evidence','evidence']]);shortcuts($('view-system'),[['History','history']])}
async function renderEngineReadiness(){const system=$('view-system');if(!system||$('engineReadinessCompact'))return;const section=document.createElement('section');section.id='engineReadinessCompact';section.innerHTML='<div class="sectionhead"><h2>Analytics Engines</h2><div class="note">Current-session defensive analytics and correlation readiness.</div></div><div class="engine-grid" id="engineGrid"><div class="engine-cell"><div class="label">Status</div><strong>LOADING</strong></div></div>';system.appendChild(section);try{const urls=['/api/v1/system/depth-engines','/api/v1/system/depth-engines-v2','/api/v1/system/depth-engines-v3','/api/v1/system/depth-engines-v4'];const results=await Promise.all(urls.map(u=>fetch(u,{cache:'no-store'}).then(r=>r.ok?r.json():null).catch(()=>null)));const dedup=new Map();for(const d of results)for(const e of(d?.engines||[]))if(e?.engine)dedup.set(String(e.engine),e);$('engineGrid').innerHTML=[...dedup.values()].map(e=>`<div class="engine-cell"><div class="label">${String(e.engine).replaceAll('_',' ')}</div><strong>${String(e.state||'ACTIVE')}</strong><div class="small">${Array.isArray(e.findings)?`${e.findings.length} findings`:e.score!==undefined?`score ${e.score}`:'current session'}</div></div>`).join('')||'<div class="engine-cell"><strong>AVAILABLE</strong></div>'}catch{$('engineGrid').innerHTML='<div class="engine-cell"><strong>UNAVAILABLE</strong></div>'}}
function tick(){compactPrimaryNav();installShortcuts();renderEngineReadiness()}
setTimeout(tick,350);setInterval(tick,2500);
})();
</script>
<script>
(()=>{
const $=id=>document.getElementById(id),token=()=>sessionStorage.getItem('campusOpsAdminToken')||'';
let history=[],lastTarget='',timer=null,phase=0;
function target(){return ($('redTarget')?.value||'').trim()}
function addPane(){const shell=document.querySelector('#view-admin-red .red-shell'),nav=shell?.querySelector('.red-subnav');if(!shell||!nav||$('redPane-live'))return;const liveBtn=document.createElement('button');liveBtn.dataset.redPane='live';liveBtn.textContent='LIVE 4D SPACE';nav.appendChild(liveBtn);const ctrlBtn=document.createElement('button');ctrlBtn.dataset.redPane='control';ctrlBtn.textContent='CONTROL';nav.appendChild(ctrlBtn);const live=document.createElement('div');live.className='red-pane';live.id='redPane-live';live.innerHTML=`<div class="red-live-grid"><div><div class="red-live-stage"><div class="red-live-hud" id="redLiveHud">LIVE 4D SPACE<br>waiting for target</div><svg id="redLiveSvg" viewBox="0 0 1100 620"></svg></div><div class="red-timebar" id="redTimebar"></div></div><div class="red-live-side"><div class="label">TEMPORAL MODEL</div><div class="red-live-stat" id="redLiveStats"></div><div class="label">RECENT CHANGES</div><div id="redLiveEvents"></div></div></div>`;shell.appendChild(live);const ctrl=document.createElement('div');ctrl.className='red-pane';ctrl.id='redPane-control';ctrl.innerHTML=`<div class="red-grid"><div class="red-panel"><div class="label">TARGET CONTROL PLANE</div><div id="redControlState"></div></div><div class="red-panel"><div class="label">MANAGED RESPONSE</div><div class="red-control-row"><div><b>Collect snapshot</b><span>Process, service, connection and host-state evidence.</span></div><button class="btn" id="redCtlSnapshot">SNAPSHOT</button></div><div class="red-control-row"><div><b>Isolate host</b><span>Managed agent applies default-block firewall policy while preserving the management channel.</span></div><button class="btn red-control-danger" id="redCtlIsolate">ISOLATE</button></div><div class="red-control-row"><div><b>Restore network</b><span>Restores the saved firewall profile state. Separate explicit operator action.</span></div><button class="btn" id="redCtlRestore">RESTORE</button></div><div class="red-warning">IP alone never grants control. These actions work only for enrolled managed endpoints. Unmanaged hosts require NAC/switch/controller integration.</div><div class="message" id="redCtlMessage" style="margin-top:10px"></div></div></div>`;shell.appendChild(ctrl);for(const b of [liveBtn,ctrlBtn])b.onclick=()=>switchPane(b.dataset.redPane);$('redCtlSnapshot').onclick=()=>action('snapshot');$('redCtlIsolate').onclick=()=>action('isolate',true);$('redCtlRestore').onclick=()=>action('restore',true)}
function switchPane(name){document.querySelectorAll('#view-admin-red [data-red-pane]').forEach(b=>b.classList.toggle('active',b.dataset.redPane===name));document.querySelectorAll('#view-admin-red .red-pane').forEach(p=>p.classList.toggle('active',p.id===`redPane-${name}`));if(name==='live')startLive();if(name==='control')refreshControl()}
async function action(kind,confirmNeeded=false){const t=target();if(!t)return;const msg=$('redCtlMessage');if(confirmNeeded&&!confirm(`${kind==='isolate'?'ISOLATE':'RESTORE'} network state for ${t}?`))return;msg.textContent='Submitting '+kind+' job...';try{const r=await fetch(`/api/v1/admin/targets/${encodeURIComponent(t)}/${kind}`,{method:'POST',headers:{'X-Campus-Admin':token()}}),d=await r.json();if(!r.ok)throw new Error(d.detail||`HTTP ${r.status}`);msg.textContent=`${kind.toUpperCase()} job queued · ${d.job?.job_id||'accepted'}`;setTimeout(refreshControl,1200)}catch(e){msg.textContent=e.message}}
async function refreshControl(){const t=target();if(!t)return;try{const r=await fetch('/api/v1/admin/targets',{cache:'no-store',headers:{'X-Campus-Admin':token()}}),d=await r.json();const row=(d.targets||[]).find(x=>String(x.ip)===t)||{};$('redControlState').innerHTML=`<div class="red-live-stat"><div><div class="label">MANAGED</div><strong>${row.managed?'YES':'NO'}</strong></div><div><div class="label">AGENT</div><strong>${row.agent_status||'NONE'}</strong></div><div><div class="label">ISOLATION</div><strong>${row.isolation_state||'UNKNOWN'}</strong></div><div><div class="label">REMOTE ENROLLED</div><strong>${row.remote_enrolled?'YES':'NO'}</strong></div></div>`;for(const id of ['redCtlSnapshot','redCtlIsolate','redCtlRestore'])$(id).disabled=!row.managed}catch(e){$('redControlState').textContent=e.message}}
function startLive(){if(timer)clearInterval(timer);sample();timer=setInterval(sample,2000)}
async function sample(){const t=target();if(!t||!$('redPane-live')?.classList.contains('active'))return;if(t!==lastTarget){history=[];lastTarget=t}try{const [r,s]=await Promise.all([fetch('/api/v1/admin/red-panel/'+encodeURIComponent(t),{cache:'no-store',headers:{'X-Campus-Admin':token()}}),fetch('/api/v1/live/status',{cache:'no-store'})]);if(!r.ok)return;const d=await r.json(),status=s.ok?await s.json():{};history.push({at:Date.now(),flows:Number(d.observed_flows||0),peers:Number(d.peer_count||0),signals:Number(d.security_signals||0),risk:Number(d.risk_score||0),model:d,status});if(history.length>40)history.shift();renderLive()}catch{}}
function renderLive(){const h=history[history.length-1];if(!h)return;phase+=.18;$('redLiveHud').innerHTML=`LIVE 4D SPACE<br>${h.model.target}<br>${history.length} temporal samples · ${h.flows} flows · ${h.peers} peers`;$('redLiveStats').innerHTML=[['RISK',h.risk],['SIGNALS',h.signals],['PEERS',h.peers],['FLOWS',h.flows]].map(x=>`<div><div class="label">${x[0]}</div><strong>${x[1]}</strong></div>`).join('');const prev=history.length>1?history[history.length-2]:h;const changes=[['flows',h.flows-prev.flows],['peers',h.peers-prev.peers],['signals',h.signals-prev.signals],['risk',h.risk-prev.risk]].filter(x=>x[1]);$('redLiveEvents').innerHTML=changes.map(x=>`<div class="red-live-event"><b>${x[0].toUpperCase()}</b> ${x[1]>0?'+':''}${x[1]} in latest sample</div>`).join('')||'<div class="muted">No material change in latest sample.</div>';renderTimeline();render4d(h.model)}
function renderTimeline(){const bar=$('redTimebar');if(!bar)return;const max=Math.max(1,...history.map(x=>x.flows));bar.innerHTML=history.map((x,i)=>`<span style="left:${(i/Math.max(1,history.length-1))*100}%;height:${Math.max(3,(x.flows/max)*34)}px;opacity:${.25+.75*(i/history.length)}"></span>`).join('')}
function render4d(d){const svg=$('redLiveSvg');if(!svg)return;const targetId=d.target,peers=(d.top_peers||[]).slice(0,18),services=(d.exposures||[]).slice(0,12);let lines='',nodes='';const cx=550,cy=310;for(let i=0;i<peers.length;i++){const a=(Math.PI*2*i/Math.max(1,peers.length))+phase,z=(i%5)*34-68,r=205+z*.55,x=cx+Math.cos(a)*r,y=cy+Math.sin(a)*r*.58-z*.32;lines+=`<line class="red-trail" x1="${cx}" y1="${cy}" x2="${x}" y2="${y}" opacity="${.3+(i%5)*.12}"/>`;nodes+=`<circle class="red-live-node" cx="${x}" cy="${y}" r="${7+(i%3)}"/><text class="red-live-label" x="${x+10}" y="${y+3}">${peers[i][0]}</text>`}for(let i=0;i<services.length;i++){const a=(Math.PI*2*i/Math.max(1,services.length))-phase*.6,r=105,x=cx+Math.cos(a)*r,y=cy+Math.sin(a)*r*.45;lines+=`<line class="red-trail" x1="${cx}" y1="${cy}" x2="${x}" y2="${y}" opacity=".55"/>`;nodes+=`<rect class="red-live-node" x="${x-7}" y="${y-7}" width="14" height="14"/><text class="red-live-label" x="${x+10}" y="${y+3}">${services[i].port}</text>`}const pulseR=34+18*Math.sin(phase*2);svg.innerHTML=`<g opacity=".22"><ellipse cx="${cx}" cy="${cy}" rx="420" ry="220" fill="none" stroke="#777" stroke-dasharray="5 9"/><ellipse cx="${cx}" cy="${cy}" rx="260" ry="130" fill="none" stroke="#555" stroke-dasharray="4 8"/></g>${lines}<circle cx="${cx}" cy="${cy}" r="${pulseR}" fill="none" stroke="#fff" opacity=".15"/><circle class="red-live-target" cx="${cx}" cy="${cy}" r="27"/><text class="red-live-target-label" x="${cx-23}" y="${cy+3}">${targetId}</text>${nodes}`}
function install(){addPane()}
setTimeout(install,700);setInterval(install,2200);
})();
</script>
<script>
(()=>{
const $=id=>document.getElementById(id),token=()=>sessionStorage.getItem('campusOpsAdminToken')||'';
function target(){return ($('redTarget')?.value||'').trim()}
function installPurple(){const shell=document.querySelector('#view-admin-red .red-shell'),nav=shell?.querySelector('.red-subnav');if(!shell||!nav||$('redPane-purple'))return;const b=document.createElement('button');b.dataset.redPane='purple';b.textContent='PURPLE TEAM';nav.appendChild(b);const pane=document.createElement('div');pane.className='red-pane';pane.id='redPane-purple';pane.innerHTML=`<div class="purple-score" id="purpleScore"><div><div class="label">COVERAGE</div><strong>—</strong></div><div><div class="label">GAP SCORE</div><strong>—</strong></div><div><div class="label">TECHNIQUES</div><strong>—</strong></div></div><div class="red-panel"><div style="display:flex;justify-content:space-between;align-items:center;gap:8px"><div class="label">ATT&CK VALIDATION MATRIX</div><button class="btn" id="purpleRefresh">REFRESH COVERAGE</button></div><div style="overflow:auto;margin-top:10px"><table class="purple-table"><thead><tr><th>TECHNIQUE</th><th>EVIDENCE</th><th>DETECTION</th><th>CONTROL</th><th>COVERAGE</th><th>GAP</th></tr></thead><tbody id="purpleRows"><tr><td colspan="6">Load a target first.</td></tr></tbody></table></div></div><div class="red-grid" style="margin-top:12px"><div class="red-panel"><div class="label">SAFE EXERCISE QUEUE</div><div id="purpleExercises"></div></div><div class="red-panel"><div class="label">VALIDATION CONTRACT</div><div id="purpleTruth" class="red-row">Evidence-backed coverage validation only.</div><div class="red-warning">This workspace validates monitoring and controls. It does not auto-exploit targets or manufacture ATT&CK execution claims.</div></div></div>`;shell.appendChild(pane);b.onclick=()=>{document.querySelectorAll('#view-admin-red [data-red-pane]').forEach(x=>x.classList.toggle('active',x.dataset.redPane==='purple'));document.querySelectorAll('#view-admin-red .red-pane').forEach(x=>x.classList.toggle('active',x.id==='redPane-purple'));loadPurple()};$('purpleRefresh').onclick=loadPurple}
async function loadPurple(){const t=target();if(!t)return;try{const r=await fetch('/api/v1/admin/red-panel/'+encodeURIComponent(t),{cache:'no-store',headers:{'X-Campus-Admin':token()}}),d=await r.json();if(!r.ok)throw new Error(d.detail||`HTTP ${r.status}`);render(d.purple_team||{})}catch(e){$('purpleRows').innerHTML=`<tr><td colspan="6">${String(e.message||e)}</td></tr>`}}
function render(p){const rows=p.techniques||[];$('purpleScore').innerHTML=`<div><div class="label">COVERAGE</div><strong>${Number(p.coverage_score||0)}%</strong></div><div><div class="label">GAP SCORE</div><strong>${Number(p.detection_gap_score||0)}%</strong></div><div><div class="label">TECHNIQUES</div><strong>${rows.filter(x=>x.technique!=='BASELINE').length}</strong></div>`;$('purpleRows').innerHTML=rows.map(x=>`<tr><td><b>${x.technique}</b><br>${x.name}</td><td>${x.evidence}<br><span class="small">${x.telemetry}</span></td><td>${String(x.detection_state||'').replaceAll('_',' ')}</td><td>${String(x.control_state||'').replaceAll('_',' ')}</td><td>${x.coverage}%</td><td class="${x.gap==='HIGH'?'purple-gap-high':''}">${x.gap}</td></tr>`).join('')||'<tr><td colspan="6">No current candidates.</td></tr>';$('purpleExercises').innerHTML=(p.exercise_queue||[]).map((x,i)=>`<div class="purple-exercise"><div class="purple-num">${i+1}</div><div>${x}</div></div>`).join('')||'<div class="muted">No exercise recommendations.</div>';$('purpleTruth').textContent=p.truth_note||'Evidence-backed validation candidates only.'}
setTimeout(installPurple,900);setInterval(installPurple,2200);
})();
</script>
"""
