from __future__ import annotations


DIAGNOSTIC_EXTENSION = r"""
<style>
.diag-toolbar{display:flex;gap:8px;align-items:center}.diag-list{display:grid;gap:9px}.diag-card{border:1px solid #c7c7c7;padding:12px}.diag-card.problem{border-left:4px solid #111}.diag-title{font-weight:800;font-size:12px}.diag-grid{display:grid;grid-template-columns:110px 1fr;margin-top:8px;border-top:1px solid #ddd}.diag-grid>div{padding:6px 4px;border-bottom:1px solid #ddd;font-size:10px;line-height:1.5}.diag-grid>div:nth-child(odd){font-size:9px;letter-spacing:.08em;text-transform:uppercase;color:#666}.diag-checks{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}.diag-check{border:1px solid #aaa;padding:4px 7px;font:9px Consolas,monospace}.diag-check.bad{border-color:#111;font-weight:700}.diag-ok{border:1px solid #c7c7c7;padding:14px;font-size:11px;line-height:1.55}
</style>
<script>
(()=>{
const D=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let last=0;
function inject(){const view=D('view-system');if(!view||D('systemDiagnosticsSection'))return;const section=document.createElement('section');section.id='systemDiagnosticsSection';section.innerHTML=`<div class="sectionhead"><div><h2>Runtime Diagnosis</h2><div class="small">MON explains detected runtime faults with evidence, likely cause, corrective action and verification.</div></div><div class="diag-toolbar"><span class="status" id="diagState">LOADING</span><button class="btn" id="diagRefresh">Refresh</button></div></div><div class="diag-list" id="diagProblems"><div class="diag-ok">Loading deterministic diagnostics…</div></div><div class="diag-checks" id="diagChecks"></div>`;view.insertBefore(section,view.firstChild);D('diagRefresh').onclick=load;load();}
async function load(){try{const response=await fetch('/api/v1/system/diagnostics',{cache:'no-store'}),data=await response.json();if(!response.ok)throw new Error(data.detail||`HTTP ${response.status}`);last=Date.now();D('diagState').textContent=data.state||'UNKNOWN';const problems=data.problems||[];D('diagProblems').innerHTML=problems.length?problems.map(p=>`<div class="diag-card problem"><div class="diag-title">${esc(p.problem||'Runtime problem')} · ${esc(p.severity||'INFO')}</div><div class="diag-grid"><div>Evidence</div><div>${esc(p.evidence||'—')}</div><div>Cause</div><div>${esc(p.cause||'—')}</div><div>Fix</div><div>${esc(p.fix||'—')}</div><div>Verify</div><div>${esc(p.verify||'—')}</div></div></div>`).join(''):'<div class="diag-ok"><b>No MON runtime fault detected.</b><br>The monitoring session, selected interface, managed TShark process and stable workers currently satisfy the runtime checks.</div>';const checks=data.checks||[];D('diagChecks').innerHTML=checks.map(c=>`<span class="diag-check ${c.ok?'':'bad'}">${esc(c.check)}=${c.ok?'OK':'FAIL'}</span>`).join('');}catch(error){D('diagState').textContent='ERROR';D('diagProblems').innerHTML=`<div class="diag-card problem"><div class="diag-title">Diagnostic API unavailable</div><div class="diag-grid"><div>Evidence</div><div>${esc(error.message)}</div><div>Fix</div><div>Check campus-ops.service and the local API before changing capture configuration.</div></div></div>`;}}
setInterval(()=>{if(document.querySelector('.tab.active')?.dataset?.view==='system'&&Date.now()-last>3500)load();},4000);inject();
})();
</script>
"""
