IOC_EXTENSION = r"""
<style>
.ioc-tab{display:none}.ioc-tab.show{display:block}.ioc-shell{max-width:1500px;margin:0 auto}.ioc-grid{display:grid;grid-template-columns:.8fr 1.2fr;gap:14px}.ioc-panel{border:1px solid #c7c7c7;padding:12px;min-width:0}.ioc-form{display:grid;grid-template-columns:120px 1fr 120px;gap:8px}.ioc-form input,.ioc-form select{height:34px;border:1px solid #999;padding:0 9px}.ioc-row{padding:8px 0;border-bottom:1px solid #ddd;font-size:10px;line-height:1.45}.ioc-row:last-child{border-bottom:0}.ioc-list{max-height:520px;overflow:auto}
@media(max-width:1000px){.ioc-grid{grid-template-columns:1fr}.ioc-form{grid-template-columns:1fr}}
</style>
<script>
(()=>{
const I=id=>document.getElementById(id);const ie=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function token(){return sessionStorage.getItem('campusOpsAdminToken')||''}function headers(json=false){const h={'X-Campus-Admin':token()};if(json)h['Content-Type']='application/json';return h}
async function api(path,options={}){options.headers={...(options.headers||{}),...headers(false)};const r=await fetch(path,options),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||`HTTP ${r.status}`);return d}
function inject(){if(I('view-admin-ioc'))return;const nav=document.querySelector('nav'),main=document.querySelector('main'),foot=main?.querySelector('.foot');if(!nav||!main)return;try{pages['admin-ioc']=['IOC Watch','Operator-managed IP, domain and SHA-256 watchlist.']}catch{}const b=document.createElement('button');b.className='tab ioc-tab';b.dataset.view='admin-ioc';b.textContent='IOC Watch';b.onclick=()=>setView('admin-ioc');nav.appendChild(b);const v=document.createElement('div');v.className='view';v.id='view-admin-ioc';v.innerHTML=`<section class="ioc-shell"><div class="sectionhead"><div><h2>IOC Watchlist</h2><div class="small">Operator-supplied defensive indicators are matched against live packet and file-analysis telemetry.</div></div><button class="btn" id="iocRefresh">Refresh</button></div><div class="ioc-grid"><div class="ioc-panel"><div class="label">Add Indicator</div><div class="ioc-form" style="margin-top:9px"><select id="iocKind"><option>IP</option><option>DOMAIN</option><option>SHA256</option></select><input id="iocValue" placeholder="Indicator value"><select id="iocSeverity"><option>HIGH</option><option>CRITICAL</option><option>MEDIUM</option><option>LOW</option></select></div><input id="iocLabel" placeholder="Label" style="width:100%;height:34px;border:1px solid #999;padding:0 9px;margin-top:8px"><input id="iocNotes" placeholder="Notes" style="width:100%;height:34px;border:1px solid #999;padding:0 9px;margin-top:8px"><div class="toolbar" style="margin-top:9px"><button class="btn" id="iocAdd">Add To Watchlist</button></div><div class="message" id="iocMessage"></div><div class="label" style="margin-top:18px">Current Watchlist</div><div id="iocList" class="ioc-list"></div></div><div class="ioc-panel"><div class="label">Live IOC Matches</div><div id="iocMatches" class="ioc-list"></div></div></div></section>`;main.insertBefore(v,foot||null);wire()}
function visible(){const b=document.querySelector('.ioc-tab');if(b)b.classList.toggle('show',!!token())}
async function refresh(){if(!token())return;try{const [a,b]=await Promise.all([api('/api/v1/admin/iocs'),api('/api/v1/admin/iocs/matches/live')]);I('iocList').innerHTML=(a.indicators||[]).map(x=>`<div class="ioc-row"><b>${ie(x.severity)} · ${ie(x.kind)}</b> · <span class="mono">${ie(x.value)}</span><br>${ie(x.label||'')}${x.notes?` · ${ie(x.notes)}`:''}<br><button class="btn" data-ioc-delete="${ie(x.indicator_id)}">Remove</button></div>`).join('')||'<div class="muted">No indicators configured.</div>';I('iocMatches').innerHTML=(b.matches||[]).map(x=>{const p=x.payload||{},e=p.evidence||{};return `<div class="ioc-row"><b>${ie(x.severity)} · ${ie(p.title||'IOC match')}</b><br>${ie(e.indicator_kind||'')} <span class="mono">${ie(e.indicator||'')}</span><br>Observed: <span class="mono">${ie(e.observable||'')}</span></div>`}).join('')||'<div class="muted">No current-session IOC matches.</div>';document.querySelectorAll('[data-ioc-delete]').forEach(btn=>btn.onclick=()=>remove(btn.dataset.iocDelete))}catch(e){I('iocMessage').textContent=e.message}}
async function add(){const body={kind:I('iocKind').value,value:I('iocValue').value.trim(),severity:I('iocSeverity').value,label:I('iocLabel').value.trim(),notes:I('iocNotes').value.trim()};if(!body.value)return;try{const r=await fetch('/api/v1/admin/iocs',{method:'POST',headers:headers(true),body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.detail||'Add failed');I('iocMessage').textContent='Indicator added.';I('iocValue').value='';await refresh()}catch(e){I('iocMessage').textContent=e.message}}
async function remove(id){if(!confirm('Remove this indicator from the watchlist?'))return;try{await api(`/api/v1/admin/iocs/${encodeURIComponent(id)}`,{method:'DELETE'});await refresh()}catch(e){I('iocMessage').textContent=e.message}}
function wire(){I('iocAdd').onclick=add;I('iocRefresh').onclick=refresh;I('iocValue').addEventListener('keydown',e=>{if(e.key==='Enter')add()})}
inject();visible();setInterval(visible,700);setInterval(()=>{if(document.querySelector('.tab.active')?.dataset?.view==='admin-ioc')refresh()},5000);
})();
</script>
"""
