PATHSPACE_EXTENSION = r"""
<style>
#view-pathspace>section{max-width:1500px;margin:0 auto}.pathspace-grid{display:grid;grid-template-columns:minmax(0,1fr) 330px;gap:14px}.pathspace-canvas-wrap{border:1px solid #c7c7c7;background:#fff;position:relative;height:700px;overflow:hidden}.pathspace-canvas{display:block;width:100%;height:100%;cursor:grab;background:#fff;touch-action:none}.pathspace-canvas.dragging{cursor:grabbing}.pathspace-hud{position:absolute;left:12px;top:12px;border:1px solid #bbb;background:rgba(255,255,255,.96);padding:8px 10px;font:10px/1.45 Consolas,monospace;z-index:3}.pathspace-hud b{display:block;font:700 10px Arial,Helvetica,sans-serif;letter-spacing:.09em;margin-bottom:4px}.pathspace-side{border:1px solid #c7c7c7;padding:13px;min-width:0}.pathspace-stat{display:grid;grid-template-columns:1fr 1fr;border-left:1px solid #d0d0d0;border-top:1px solid #d0d0d0;margin:10px 0}.pathspace-stat>div{padding:9px;border-right:1px solid #d0d0d0;border-bottom:1px solid #d0d0d0}.pathspace-stat strong{display:block;font-size:16px;margin-top:3px}.pathspace-list{max-height:320px;overflow:auto}.pathspace-row{border-bottom:1px solid #ddd;padding:7px 0;font:10px/1.45 Consolas,monospace}.pathspace-tools{display:flex;gap:7px;flex-wrap:wrap}.pathspace-note{font-size:10px;color:#555;line-height:1.5;margin-top:8px}.ps-edge{stroke:#bdbdbd;stroke-width:1;opacity:.45}.ps-edge.hot{stroke:#111;opacity:.92;stroke-width:1.8}.ps-node{cursor:pointer}.ps-node circle{fill:#fff;stroke:#111;stroke-width:1.1}.ps-node.selected circle{fill:#111;stroke-width:2}.ps-node text{font:9px Consolas,monospace;fill:#111;pointer-events:none}.ps-node.selected text{fill:#111;font-weight:700}.ps-layer{fill:none;stroke:#ddd;stroke-width:1;stroke-dasharray:5 8}.ps-layer-label{font:700 9px Arial,Helvetica,sans-serif;letter-spacing:.12em;fill:#777}.ps-pulse{fill:#111}.ps-empty{font:700 15px Arial,Helvetica,sans-serif;fill:#555;letter-spacing:.08em}@media(max-width:1100px){.pathspace-grid{grid-template-columns:1fr}.pathspace-canvas-wrap{height:600px}}
</style>
<script>
(()=>{
const P=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data=null,nodes=[],edges=[],yaw=-.58,pitch=.32,zoom=1,drag=false,moved=false,lastX=0,lastY=0,selected='',lastFetch=0,physicalCount=0,frame=0;
function inject(){if(P('view-pathspace'))return;const nav=document.querySelector('nav'),main=document.querySelector('main'),topo=document.querySelector('.tab[data-view="topology"]'),foot=main?.querySelector('.foot');if(!nav||!main)return;try{pages['pathspace']=['Path Space','Interactive depth map of current-session communication paths.']}catch{}const b=document.createElement('button');b.className='tab';b.dataset.view='pathspace';b.textContent='PATH SPACE';b.onclick=()=>setView('pathspace');if(topo?.nextSibling)nav.insertBefore(b,topo.nextSibling);else nav.appendChild(b);const v=document.createElement('div');v.className='view';v.id='view-pathspace';v.innerHTML=`<section><div class="sectionhead"><div><h2>Network Path Space</h2><div class="small">3D projection of current-session communication. Drag to rotate, wheel to zoom, click a node to inspect.</div></div><div class="pathspace-tools"><button class="btn" id="pathReset">Reset Camera</button><button class="btn" id="pathRefresh">Refresh</button></div></div><div class="pathspace-grid"><div class="pathspace-canvas-wrap"><svg id="pathCanvas" class="pathspace-canvas" viewBox="0 0 1100 700" preserveAspectRatio="xMidYMid meet"></svg><div class="pathspace-hud"><b>LIVE PATH SPACE</b><span id="pathHud">Waiting for live topology…</span></div></div><aside class="pathspace-side"><div class="label">Selected Node</div><h3 id="pathSelected" style="margin:7px 0 4px">None</h3><div class="small" id="pathSelectedMeta">Click a node.</div><div class="pathspace-stat" id="pathStats"></div><div class="label">Observed Relationships</div><div class="pathspace-list" id="pathPeers"></div><div class="label" style="margin-top:12px">Visibility Contract</div><div class="pathspace-note" id="pathTruth">Physical hops are asserted only when infrastructure telemetry verifies them.</div></aside></div></section>`;main.insertBefore(v,foot||null);wire();load();requestAnimationFrame(animate)}
function role(a){const s=String(a?.role||a?.classification||'').toUpperCase();if(s.includes('SENSOR'))return'sensor';if(s.includes('INFRA')||s.includes('GATEWAY')||s.includes('SWITCH')||s.includes('ROUTER'))return'infra';if(s.includes('PUBLIC')||s.includes('OFF_SUBNET')||s.includes('EXTERNAL'))return'external';return'local'}
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function weight(e){return Number(e.bps_ewma||0)+Number(e.packets||0)*100}
function rebuild(d){data=d;const live=d.live||{},assets=live.assets||[],raw=live.topology_edges||[],amap=new Map(assets.map(a=>[String(a.ip||a.id||''),a]));const scores={};for(const e of raw){scores[String(e.source||'')]=(scores[String(e.source||'')]||0)+weight(e);scores[String(e.target||'')]=(scores[String(e.target||'')]||0)+weight(e)}let ids=[...new Set([...amap.keys(),...raw.flatMap(e=>[String(e.source||''),String(e.target||'')])].filter(Boolean))];const sensors=ids.filter(id=>role(amap.get(id))==='sensor'),rest=ids.filter(id=>!sensors.includes(id)).sort((a,b)=>(scores[b]||0)-(scores[a]||0));ids=[...sensors,...rest.slice(0,139)];const visible=new Set(ids),layers={sensor:-270,local:-80,infra:120,external:300};nodes=ids.map(id=>{const a=amap.get(id)||{},r=role(a),seed=hash(id),angle=((seed%10000)/10000)*Math.PI*2,ring=r==='sensor'?35:r==='infra'?150:r==='local'?275:390,j=((seed>>8)%90)-45;return{id,a,r,x:Math.cos(angle)*(ring+j*.25),y:Math.sin(angle)*(ring+j*.25),z:layers[r]+(((seed>>16)%70)-35)}});const nmap=new Map(nodes.map(n=>[n.id,n]));edges=raw.filter(e=>visible.has(String(e.source||''))&&visible.has(String(e.target||''))).sort((a,b)=>weight(b)-weight(a)).slice(0,260).map(e=>({a:nmap.get(String(e.source)),b:nmap.get(String(e.target)),raw:e})).filter(e=>e.a&&e.b);renderStats();renderSelected();render()}
function project(n){let x=n.x,y=n.y,z=n.z,cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch),x1=x*cy-z*sy,z1=x*sy+z*cy,y1=y,y2=y1*cp-z1*sp,z2=y1*sp+z1*cp,den=Math.max(260,900+z2),f=720*zoom/den;return{x:550+x1*f,y:350+y2*f,z:z2,f}}
function layerGuide(z,label){const p1=project({x:-430,y:-300,z}),p2=project({x:430,y:-300,z}),p3=project({x:430,y:300,z}),p4=project({x:-430,y:300,z});return`<polygon class="ps-layer" points="${p1.x},${p1.y} ${p2.x},${p2.y} ${p3.x},${p3.y} ${p4.x},${p4.y}"></polygon><text class="ps-layer-label" x="${p4.x+8}" y="${p4.y-8}">${label}</text>`}
function render(){const svg=P('pathCanvas');if(!svg)return;if(!nodes.length){svg.innerHTML='<rect width="1100" height="700" fill="#fff"></rect><text class="ps-empty" x="550" y="350" text-anchor="middle">WAITING FOR LIVE TOPOLOGY</text>';return}const ps=new Map(nodes.map(n=>[n.id,project(n)]));const guides=layerGuide(-270,'SENSOR')+layerGuide(-80,'LOCAL / VLAN')+layerGuide(120,'INFRASTRUCTURE')+layerGuide(300,'EXTERNAL');const es=edges.map((e,i)=>{const a=ps.get(e.a.id),b=ps.get(e.b.id),hot=i<18||Date.now()-new Date(e.raw.last_seen||0).getTime()<7000;return`<line class="ps-edge ${hot?'hot':''}" x1="${a.x.toFixed(1)}" y1="${a.y.toFixed(1)}" x2="${b.x.toFixed(1)}" y2="${b.y.toFixed(1)}"></line>`}).join('');const sorted=[...nodes].sort((a,b)=>ps.get(a.id).z-ps.get(b.id).z),ns=sorted.map(n=>{const p=ps.get(n.id),sel=n.id===selected,r=Math.max(3.5,6*p.f),label=String(n.a.hostname||n.id),short=label.length>18?label.slice(0,17)+'…':label;return`<g class="ps-node ${sel?'selected':''}" data-ps-node="${esc(n.id)}"><circle cx="${p.x.toFixed(1)}" cy="${p.y.toFixed(1)}" r="${r.toFixed(1)}"></circle>${sel||p.f>.72?`<text x="${(p.x+r+4).toFixed(1)}" y="${(p.y+3).toFixed(1)}">${esc(short)}</text>`:''}</g>`}).join('');svg.innerHTML='<rect width="1100" height="700" fill="#fff"></rect>'+guides+es+ns;svg.querySelectorAll('[data-ps-node]').forEach(g=>g.onclick=e=>{e.stopPropagation();selected=g.dataset.psNode||'';renderSelected();render()})}
function renderStats(){const by={sensor:0,infra:0,local:0,external:0};nodes.forEach(n=>by[n.r]++);P('pathStats').innerHTML=[['Nodes',nodes.length],['Links',edges.length],['Local',by.local],['External',by.external],['Infra',by.infra],['Sensor',by.sensor]].map(x=>`<div><div class="label">${esc(x[0])}</div><strong>${esc(x[1])}</strong></div>`).join('');P('pathHud').textContent=`${nodes.length} visible nodes · ${edges.length} links · yaw ${yaw.toFixed(2)} · pitch ${pitch.toFixed(2)} · zoom ${zoom.toFixed(2)}`}
function renderSelected(){const n=nodes.find(x=>x.id===selected);if(!n){P('pathSelected').textContent='None';P('pathSelectedMeta').textContent='Click a node.';P('pathPeers').innerHTML='<div class="muted">No node selected.</div>';return}P('pathSelected').textContent=n.id;P('pathSelectedMeta').textContent=`${n.r.toUpperCase()} · ${n.a.hostname||n.a.classification||n.a.role||'observed node'}`;const rel=edges.filter(e=>e.a.id===n.id||e.b.id===n.id).sort((a,b)=>weight(b.raw)-weight(a.raw)).slice(0,40);P('pathPeers').innerHTML=rel.map(e=>{const peer=e.a.id===n.id?e.b.id:e.a.id,proto=e.raw.last_protocol||e.raw.protocol||e.raw.transport||'';return`<div class="pathspace-row"><b>${esc(peer)}</b><br>${esc(proto)} · ${Number(e.raw.packets||0).toLocaleString()} packets</div>`}).join('')||'<div class="muted">No observed relationships.</div>'}
async function load(){try{const r=await fetch('/api/v1/live/status',{cache:'no-store'}),d=await r.json();if(r.ok)rebuild(d);try{const p=await fetch('/api/v1/system/physical-topology-evidence',{cache:'no-store'}),pd=await p.json();physicalCount=(pd.links||pd.physical_links||[]).length}catch{physicalCount=0}P('pathTruth').textContent=physicalCount?`${physicalCount} infrastructure link(s) are evidence-backed. Other lines remain observed communication relationships.`:'No verified physical-hop telemetry is available. This is a communication-space projection, not a claimed switch/router path.'}catch(e){P('pathHud').textContent=`PATH SPACE ERROR · ${e.message}`}finally{lastFetch=Date.now()}}
function wire(){const svg=P('pathCanvas');svg.addEventListener('pointerdown',e=>{drag=true;moved=false;lastX=e.clientX;lastY=e.clientY;svg.setPointerCapture?.(e.pointerId);svg.classList.add('dragging')});svg.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-lastX,dy=e.clientY-lastY;if(Math.abs(dx)+Math.abs(dy)>2)moved=true;yaw+=dx*.006;pitch=Math.max(-1.15,Math.min(1.15,pitch+dy*.006));lastX=e.clientX;lastY=e.clientY;renderStats();render()});svg.addEventListener('pointerup',e=>{drag=false;svg.releasePointerCapture?.(e.pointerId);svg.classList.remove('dragging')});svg.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.5,Math.min(2.2,zoom*(e.deltaY>0?.9:1.1)));renderStats();render()},{passive:false});P('pathReset').onclick=()=>{yaw=-.58;pitch=.32;zoom=1;selected='';renderStats();renderSelected();render()};P('pathRefresh').onclick=load;setInterval(()=>{if(document.querySelector('.tab.active')?.dataset?.view==='pathspace'&&Date.now()-lastFetch>3500)load()},4000)}
function animate(){frame++;if(frame%20===0&&document.querySelector('.tab.active')?.dataset?.view==='pathspace')render();requestAnimationFrame(animate)}
inject();
})();
</script>
"""
