PATHSPACE_EXTENSION = r"""
<style>
#view-pathspace>section{max-width:1500px;margin:0 auto}.pathspace-grid{display:grid;grid-template-columns:minmax(0,1fr) 330px;gap:14px}.pathspace-canvas-wrap{border:1px solid #c7c7c7;background:#fff;position:relative;min-height:700px;overflow:hidden}.pathspace-canvas{display:block;width:100%;height:700px;cursor:grab;background:#fff}.pathspace-canvas.dragging{cursor:grabbing}.pathspace-hud{position:absolute;left:12px;top:12px;border:1px solid #bbb;background:rgba(255,255,255,.94);padding:8px 10px;font:10px/1.45 Consolas,monospace}.pathspace-hud b{display:block;font:700 10px Arial,Helvetica,sans-serif;letter-spacing:.09em;margin-bottom:4px}.pathspace-side{border:1px solid #c7c7c7;padding:13px;min-width:0}.pathspace-stat{display:grid;grid-template-columns:1fr 1fr;border-left:1px solid #d0d0d0;border-top:1px solid #d0d0d0;margin:10px 0}.pathspace-stat>div{padding:9px;border-right:1px solid #d0d0d0;border-bottom:1px solid #d0d0d0}.pathspace-stat strong{display:block;font-size:16px;margin-top:3px}.pathspace-list{max-height:320px;overflow:auto}.pathspace-row{border-bottom:1px solid #ddd;padding:7px 0;font:10px/1.45 Consolas,monospace}.pathspace-tools{display:flex;gap:7px;flex-wrap:wrap}.pathspace-note{font-size:10px;color:#555;line-height:1.5;margin-top:8px}@media(max-width:1100px){.pathspace-grid{grid-template-columns:1fr}.pathspace-canvas,.pathspace-canvas-wrap{min-height:600px;height:600px}}
</style>
<script>
(()=>{
const P=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data=null,nodes=[],edges=[],yaw=-0.62,pitch=0.44,zoom=1.0,drag=false,lastX=0,lastY=0,selected=null,anim=0,lastFetch=0;
function inject(){
 if(P('view-pathspace'))return;
 const nav=document.querySelector('nav'),main=document.querySelector('main'),topo=document.querySelector('.tab[data-view="topology"]'),foot=main?.querySelector('.foot');if(!nav||!main)return;
 try{pages['pathspace']=['Path Space','Interactive depth map of current-session communication paths.']}catch{}
 const b=document.createElement('button');b.className='tab';b.dataset.view='pathspace';b.textContent='PATH SPACE';b.onclick=()=>setView('pathspace');if(topo?.nextSibling)nav.insertBefore(b,topo.nextSibling);else nav.appendChild(b);
 const v=document.createElement('div');v.className='view';v.id='view-pathspace';v.innerHTML=`<section><div class="sectionhead"><div><h2>Network Path Space</h2><div class="small">Interactive 3D projection of live communication relationships. Drag to rotate, wheel to zoom, click a node to inspect.</div></div><div class="pathspace-tools"><button class="btn" id="pathReset">Reset Camera</button><button class="btn" id="pathRefresh">Refresh</button></div></div><div class="pathspace-grid"><div class="pathspace-canvas-wrap"><canvas id="pathCanvas" class="pathspace-canvas"></canvas><div class="pathspace-hud"><b>LIVE PATH SPACE</b><span id="pathHud">Waiting for live topology…</span></div></div><aside class="pathspace-side"><div class="label">Selected Node</div><h3 id="pathSelected" style="margin:7px 0 4px">None</h3><div class="small" id="pathSelectedMeta">Click a node.</div><div class="pathspace-stat" id="pathStats"></div><div class="label">Observed Relationships</div><div class="pathspace-list" id="pathPeers"></div><div class="label" style="margin-top:12px">Visibility Contract</div><div class="pathspace-note" id="pathTruth">Observed packet/flow relationships are visualized in depth. Physical hops are shown only when infrastructure telemetry verifies them.</div></aside></div></section>`;main.insertBefore(v,foot||null);wire();resize();load();requestAnimationFrame(draw);
}
function role(a){const s=String(a?.role||a?.classification||'').toUpperCase();if(s.includes('SENSOR'))return 'sensor';if(s.includes('INFRA')||s.includes('GATEWAY'))return 'infra';if(s.includes('PUBLIC')||s.includes('OFF_SUBNET'))return 'external';return 'local'}
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function rebuild(d){data=d;const live=d.live||{},assets=live.assets||[],rawEdges=live.topology_edges||[];const amap=new Map(assets.map(a=>[String(a.ip||a.id||''),a]));const ids=[...new Set([...amap.keys(),...rawEdges.flatMap(e=>[String(e.source||''),String(e.target||'')])].filter(Boolean))];const layerZ={sensor:-260,local:-70,infra:115,external:285};nodes=ids.map((id,i)=>{const a=amap.get(id)||{},r=role(a),seed=hash(id),angle=((seed%10000)/10000)*Math.PI*2,ring=r==='sensor'?45:r==='infra'?150:r==='local'?270:390,jitter=((seed>>8)%100)-50;return{id,a,r,x:Math.cos(angle)*(ring+jitter*.35),y:Math.sin(angle)*(ring+jitter*.35),z:layerZ[r]+(((seed>>16)%80)-40)} });const nmap=new Map(nodes.map(n=>[n.id,n]));edges=rawEdges.map(e=>({a:nmap.get(String(e.source||'')),b:nmap.get(String(e.target||'')),raw:e})).filter(e=>e.a&&e.b);renderStats();renderSelected()}
function renderStats(){const by={sensor:0,infra:0,local:0,external:0};nodes.forEach(n=>by[n.r]++);if(P('pathStats'))P('pathStats').innerHTML=[['Nodes',nodes.length],['Links',edges.length],['Local',by.local],['External',by.external],['Infra',by.infra],['Sensor',by.sensor]].map(x=>`<div><div class="label">${esc(x[0])}</div><strong>${esc(x[1])}</strong></div>`).join('');if(P('pathHud'))P('pathHud').textContent=`${nodes.length} nodes · ${edges.length} links · yaw ${yaw.toFixed(2)} · pitch ${pitch.toFixed(2)}`}
function project(n,w,h){let x=n.x,y=n.y,z=n.z;const cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch);const x1=x*cy-z*sy,z1=x*sy+z*cy,y1=y;const y2=y1*cp-z1*sp,z2=y1*sp+z1*cp;const f=720*zoom/(720+z2);return{x:w/2+x1*f,y:h/2+y2*f,z:z2,f}}
function resize(){const c=P('pathCanvas');if(!c)return;const r=c.getBoundingClientRect(),dpr=Math.min(2,window.devicePixelRatio||1);c.width=Math.max(1,Math.floor(r.width*dpr));c.height=Math.max(1,Math.floor(r.height*dpr));c._dpr=dpr}
function draw(t){const c=P('pathCanvas');if(!c){requestAnimationFrame(draw);return}const dpr=c._dpr||1,ctx=c.getContext('2d'),w=c.width/dpr,h=c.height/dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);
 const ps=new Map(nodes.map(n=>[n.id,project(n,w,h)]));
 ctx.lineWidth=1;for(const e of edges){const a=ps.get(e.a.id),b=ps.get(e.b.id),recent=Date.now()-new Date(e.raw.last_seen||0).getTime()<9000,rate=Number(e.raw.bps_ewma||0);ctx.strokeStyle=recent?'rgba(0,0,0,.55)':'rgba(0,0,0,.12)';ctx.lineWidth=recent?Math.min(3,1+Math.log10(1+rate)/3):1;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();if(recent){const q=((t/1600)+(hash(e.a.id+e.b.id)%100)/100)%1,x=a.x+(b.x-a.x)*q,y=a.y+(b.y-a.y)*q;ctx.fillStyle='#111';ctx.beginPath();ctx.arc(x,y,2.2,0,Math.PI*2);ctx.fill()}}
 const sorted=[...nodes].sort((a,b)=>ps.get(a.id).z-ps.get(b.id).z);for(const n of sorted){const p=ps.get(n.id),sel=n.id===selected,r=Math.max(3,5.5*p.f);ctx.fillStyle=sel?'#111':'#fff';ctx.strokeStyle='#111';ctx.lineWidth=sel?2:1;ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fill();ctx.stroke();if(sel||p.f>.78){ctx.fillStyle=sel?'#111':'#333';ctx.font='9px Consolas,monospace';ctx.fillText(n.id,p.x+r+4,p.y+3)}}
 anim=requestAnimationFrame(draw)}
function renderSelected(){const n=nodes.find(x=>x.id===selected);if(!n){if(P('pathSelected'))P('pathSelected').textContent='None';if(P('pathSelectedMeta'))P('pathSelectedMeta').textContent='Click a node.';if(P('pathPeers'))P('pathPeers').innerHTML='<div class="muted">No node selected.</div>';return}P('pathSelected').textContent=n.id;P('pathSelectedMeta').textContent=`${n.r.toUpperCase()} · ${n.a.hostname||n.a.classification||n.a.role||'observed node'}`;const rel=edges.filter(e=>e.a.id===n.id||e.b.id===n.id).slice().sort((a,b)=>Number(b.raw.bps_ewma||b.raw.packets||0)-Number(a.raw.bps_ewma||a.raw.packets||0)).slice(0,40);P('pathPeers').innerHTML=rel.map(e=>{const peer=e.a.id===n.id?e.b.id:e.a.id,proto=e.raw.last_protocol||e.raw.protocol||e.raw.transport||'';return`<div class="pathspace-row"><b>${esc(peer)}</b><br>${esc(proto)} · ${Number(e.raw.packets||0).toLocaleString()} packets</div>`}).join('')||'<div class="muted">No observed relationships.</div>'}
async function load(){try{const r=await fetch('/api/v1/live/status',{cache:'no-store'}),d=await r.json();if(r.ok)rebuild(d);try{const p=await fetch('/api/v1/system/physical-topology-evidence',{cache:'no-store'}),pd=await p.json();const count=(pd.links||pd.physical_links||[]).length;if(P('pathTruth'))P('pathTruth').textContent=count?`${count} physical infrastructure link(s) are evidence-backed. Remaining lines are observed communication relationships.`:'No verified physical-hop telemetry is currently available. This view is a 3D communication-path projection, not a claimed switch/router path.';}catch{}}catch{}finally{lastFetch=Date.now()}}
function nearest(ev){const c=P('pathCanvas'),r=c.getBoundingClientRect(),w=r.width,h=r.height,mx=ev.clientX-r.left,my=ev.clientY-r.top;let best=null,dist=18;for(const n of nodes){const p=project(n,w,h),d=Math.hypot(mx-p.x,my-p.y);if(d<dist){dist=d;best=n}}return best}
function wire(){const c=P('pathCanvas');c.addEventListener('mousedown',e=>{drag=true;lastX=e.clientX;lastY=e.clientY;c.classList.add('dragging')});window.addEventListener('mouseup',()=>{drag=false;c.classList.remove('dragging')});window.addEventListener('mousemove',e=>{if(!drag)return;yaw+=(e.clientX-lastX)*.006;pitch=Math.max(-1.2,Math.min(1.2,pitch+(e.clientY-lastY)*.006));lastX=e.clientX;lastY=e.clientY;renderStats()});c.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.45,Math.min(2.3,zoom*(e.deltaY>0?.9:1.1)));renderStats()},{passive:false});c.addEventListener('click',e=>{if(Math.abs(e.clientX-lastX)>4||Math.abs(e.clientY-lastY)>4)return;const n=nearest(e);if(n){selected=n.id;renderSelected()}});P('pathReset').onclick=()=>{yaw=-.62;pitch=.44;zoom=1;selected=null;renderStats();renderSelected()};P('pathRefresh').onclick=load;window.addEventListener('resize',resize);setInterval(()=>{if(document.querySelector('.tab.active')?.dataset?.view==='pathspace'&&Date.now()-lastFetch>3500)load()},4000)}
inject();
})();
</script>
"""
