from __future__ import annotations


PATHSPACE_EXTENSION = r"""
<style>
#view-pathspace>section{max-width:1500px;margin:0 auto}.pathspace-head{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.pathspace-head input{height:33px;border:1px solid #999;padding:0 9px;font:11px Consolas,monospace;min-width:260px}.pathspace-summary{display:grid;grid-template-columns:repeat(5,1fr);border-top:1px solid #c7c7c7;border-left:1px solid #c7c7c7;margin:12px 0}.pathspace-summary>div{padding:11px;border-right:1px solid #c7c7c7;border-bottom:1px solid #c7c7c7;min-height:70px}.pathspace-summary strong{display:block;font-size:17px;margin-top:5px}.pathspace-layout{display:grid;grid-template-columns:330px minmax(0,1fr);gap:14px}.pathspace-panel{border:1px solid #c7c7c7;padding:13px;min-width:0}.pathspace-targets{max-height:560px;overflow:auto}.pathspace-target{border-bottom:1px solid #ddd;padding:8px 0;cursor:pointer;font:10px/1.45 Consolas,monospace}.pathspace-target:hover{background:#f6f6f6}.pathspace-target b{display:block;font-size:11px}.pathspace-contract{border:1px solid #c7c7c7;padding:10px 12px;margin:12px 0;font-size:10px;line-height:1.55}.pathspace-row{display:grid;grid-template-columns:90px 150px 90px minmax(130px,1fr) 90px 90px 90px 140px;gap:7px;border-bottom:1px solid #ddd;padding:8px 3px;font:10px/1.4 Consolas,monospace;align-items:start}.pathspace-row.head{font:700 9px Arial,Helvetica,sans-serif;text-transform:uppercase;letter-spacing:.08em;color:#666;position:sticky;top:0;background:#fff}.pathspace-rows{max-height:520px;overflow:auto}.pathspace-empty{padding:20px;color:#666;font-size:10px}.pathspace-anomaly{font-weight:700}.pathspace-truth{font:10px/1.5 Consolas,monospace;white-space:pre-wrap}
@media(max-width:1050px){.pathspace-layout{grid-template-columns:1fr}.pathspace-summary{grid-template-columns:repeat(3,1fr)}}@media(max-width:650px){.pathspace-summary{grid-template-columns:1fr 1fr}.pathspace-row{grid-template-columns:1fr 1fr}}
</style>
<script>
(()=>{
const P=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let current='',lastTargetsAt=0;
async function api(path){const response=await fetch(path,{cache:'no-store'});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail||data));return data;}
function inject(){
  if(P('view-pathspace'))return;
  const nav=document.querySelector('nav'),main=document.querySelector('main'),topo=nav?.querySelector('button.tab[data-view="topology"]'),foot=main?.querySelector('.foot');if(!nav||!main)return;
  try{pages.pathspace=['Path Space','Evidence-backed communication paths and known network boundary.']}catch{}
  const button=document.createElement('button');button.className='tab';button.dataset.view='pathspace';button.textContent='Path Space';button.onclick=()=>{setView('pathspace');loadTargets();};if(topo?.nextSibling)nav.insertBefore(button,topo.nextSibling);else nav.appendChild(button);
  const view=document.createElement('div');view.className='view';view.id='view-pathspace';view.innerHTML=`<section><div class="sectionhead"><div><h2>Path Space</h2><div class="small">Who communicated with whom, through which known boundary, and what evidence makes the path interesting.</div></div><div class="pathspace-head"><input id="pathTarget" placeholder="Observed IP"><button class="btn" id="pathAnalyze">Analyze Path</button><button class="btn" id="pathInvestigate">Investigate</button><button class="btn" id="pathRefresh">Refresh</button></div></div><div class="pathspace-summary" id="pathSummary"></div><div class="pathspace-contract" id="pathContract">Select an observed target. MON reports communication relationships from packets; it does not invent physical switch/router hops.</div><div class="pathspace-layout"><aside class="pathspace-panel"><div class="label">Observed Targets</div><div class="pathspace-targets" id="pathTargets"><div class="pathspace-empty">Loading…</div></div></aside><div class="pathspace-panel"><div class="label">Observed Relationships</div><div class="pathspace-rows" id="pathRows"><div class="pathspace-empty">No target selected.</div></div><div class="label" style="margin-top:14px">Truth / Boundary</div><div class="pathspace-truth" id="pathTruth">No path report loaded.</div></div></div></section>`;main.insertBefore(view,foot||null);
  P('pathAnalyze').onclick=()=>analyze(P('pathTarget').value);P('pathTarget').addEventListener('keydown',e=>{if(e.key==='Enter')analyze(e.currentTarget.value)});P('pathInvestigate').onclick=()=>{const target=P('pathTarget').value.trim();if(target&&typeof window.openInvestigation==='function')window.openInvestigation(target)};P('pathRefresh').onclick=()=>{loadTargets(true);if(current)analyze(current)};
  window.openPathSpace=target=>{target=String(target||'').trim();if(target)P('pathTarget').value=target;setView('pathspace');loadTargets();if(target)analyze(target);};
  loadTargets();
}
function summary(label,value){return`<div><div class="label">${esc(label)}</div><strong>${esc(value)}</strong></div>`}
async function loadTargets(force=false){if(!force&&Date.now()-lastTargetsAt<4000)return;try{const data=await api('/api/v1/operator/targets'),targets=data.targets||[];lastTargetsAt=Date.now();P('pathTargets').innerHTML=targets.map(item=>`<div class="pathspace-target" data-path-target="${esc(item.ip)}"><b>${esc(item.ip)}</b>${esc(item.classification||'OBSERVED_PEER')} · ${Number(item.packets||0).toLocaleString()} packets</div>`).join('')||'<div class="pathspace-empty">No packet-observed targets yet.</div>';P('pathTargets').querySelectorAll('[data-path-target]').forEach(row=>row.onclick=()=>{const target=row.dataset.pathTarget||'';P('pathTarget').value=target;analyze(target)});}catch(error){P('pathTargets').innerHTML=`<div class="pathspace-empty">${esc(error.message)}</div>`}}
async function analyze(target){target=String(target||'').trim();if(!target)return;current=target;P('pathRows').innerHTML='<div class="pathspace-empty">Building path report…</div>';try{const data=await api(`/api/v1/pathspace/${encodeURIComponent(target)}`),truth=data.truth||{},rels=data.relationships||[];P('pathSummary').innerHTML=summary('Target',data.target||target)+summary('Truth',truth.status|| (truth.observed?'OBSERVED':'NOT OBSERVED'))+summary('Relationships',rels.length)+summary('Known Boundary',data.known_boundary||'NONE')+summary('Physical Hops',data.physical_hops_verified?'VERIFIED':'NOT VERIFIED');P('pathContract').textContent=data.statement||'Current-session packet relationships only.';P('pathTruth').textContent=`observed=${Boolean(truth.observed)}\nlocal_scope=${Boolean(truth.local_scope)}\nconfirmed_local_asset=${Boolean(truth.confirmed_local_asset)}\nmonitor_host=${Boolean(truth.is_monitor_host)}\ngateway=${Boolean(truth.is_gateway)}\nknown_boundary=${data.known_boundary||'none'}\nphysical_hops_verified=${Boolean(data.physical_hops_verified)}`;if(!rels.length){P('pathRows').innerHTML='<div class="pathspace-empty">No packet-observed communication relationship can be asserted for this target.</div>';return}P('pathRows').innerHTML='<div class="pathspace-row head"><span>Direction</span><span>Peer</span><span>Protocol</span><span>Application</span><span>Port</span><span>Packets</span><span>Bytes</span><span>Anomalies</span></div>'+rels.map(rel=>`<div class="pathspace-row"><span>${esc(rel.direction||'—')}</span><span>${esc(rel.peer||'—')}</span><span>${esc(rel.protocol||'—')}</span><span>${esc(rel.application||'—')}</span><span>${esc(rel.destination_port||'—')}</span><span>${Number(rel.packets||0).toLocaleString()}</span><span>${Number(rel.bytes||0).toLocaleString()}</span><span class="${(rel.anomalies||[]).length?'pathspace-anomaly':''}">${(rel.anomalies||[]).length}</span></div>`).join('');}catch(error){P('pathRows').innerHTML=`<div class="pathspace-empty">${esc(error.message)}</div>`;P('pathSummary').innerHTML='';P('pathTruth').textContent='No path report available.'}}
inject();
})();
</script>
"""
