RED_PANEL_EXTENSION = r"""
<style>
.red-shell{max-width:1500px;margin:0 auto}.red-targetbar{display:grid;grid-template-columns:minmax(260px,460px) auto auto;gap:8px}.red-targetbar input{height:35px;border:1px solid #999;padding:0 10px;font:12px Consolas,monospace}.red-hero{display:grid;grid-template-columns:repeat(5,1fr);border-left:1px solid #c7c7c7;border-top:1px solid #c7c7c7;margin:14px 0}.red-hero>div{padding:11px;border-right:1px solid #c7c7c7;border-bottom:1px solid #c7c7c7}.red-hero strong{display:block;font-size:18px;margin-top:4px}.red-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.red-panel{border:1px solid #c7c7c7;padding:13px}.red-row{padding:8px 0;border-bottom:1px solid #ddd;font-size:10px;line-height:1.45}.red-row:last-child{border-bottom:0}.red-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}@media(max-width:1000px){.red-grid{grid-template-columns:1fr}.red-hero{grid-template-columns:1fr 1fr}.red-targetbar{grid-template-columns:1fr}}
</style>
<script>
(()=>{
const R=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function token(){return sessionStorage.getItem('campusOpsAdminToken')||''}
function inject(){if(R('view-admin-red'))return;const nav=document.querySelector('nav'),main=document.querySelector('main'),foot=main?.querySelector('.foot');if(!nav||!main||typeof pages==='undefined')return;pages['admin-red']=['Red Panel','Authorized adversary-emulation planning and validation.'];const b=document.createElement('button');b.className='tab admin-tab show';b.dataset.view='admin-red';b.textContent='RED-PANEL';b.onclick=()=>setView('admin-red');nav.appendChild(b);const v=document.createElement('div');v.className='view';v.id='view-admin-red';v.innerHTML=`<section class="red-shell"><div class="sectionhead"><div><h2>RED-PANEL</h2><div class="small">Authorized validation workspace. It builds an evidence-backed attack-surface view and validation plan without auto-exploitation.</div></div></div><div class="red-targetbar"><input id="redTarget" placeholder="Target IP"><button class="btn" id="redLoad">Build Exposure View</button><button class="btn" id="redInvestigate">Open Investigation</button></div><div class="message" id="redMessage" style="margin-top:8px"></div><div class="red-hero" id="redHero"></div><div class="red-grid"><div class="red-panel"><div class="label">Observed Attack Surface</div><div id="redExposure"></div></div><div class="red-panel"><div class="label">Adversary Hypotheses</div><div id="redHypotheses"></div></div></div><div class="red-grid" style="margin-top:14px"><div class="red-panel"><div class="label">Top Peers</div><div id="redPeers"></div></div><div class="red-panel"><div class="label">Validation Controls</div><div id="redControls"></div><div class="red-actions"><button class="btn" id="redForensics">Open Forensics</button><button class="btn" id="redContain">Open Containment</button></div></div></div><div class="red-panel" style="margin-top:14px"><div class="label">Guardrails</div><div id="redGuardrails"></div></div></section>`;main.insertBefore(v,foot||null);R('redLoad').onclick=load;R('redInvestigate').onclick=()=>pivot('investigation');R('redForensics').onclick=()=>pivot('admin-forensics');R('redContain').onclick=()=>pivot('admin-contain');R('redTarget').addEventListener('keydown',e=>{if(e.key==='Enter')load()})}
function current(){return (R('redTarget')?.value||'').trim()}
function pivot(view){const t=current();if(!t)return;if(view==='investigation'&&typeof window.openInvestigation==='function'){window.openInvestigation(t);return}if(view==='admin-forensics'){const x=R('adminForensicTarget');if(x)x.value=t}if(view==='admin-contain'){const x=R('adminContainTarget');if(x)x.value=t}try{setView(view)}catch{}}
async function load(){const t=current();if(!t)return;R('redMessage').textContent='Building evidence-backed exposure view...';try{const r=await fetch('/api/v1/admin/red-panel/'+encodeURIComponent(t),{cache:'no-store',headers:{'X-Campus-Admin':token()}}),d=await r.json();if(!r.ok)throw new Error(d.detail||`HTTP ${r.status}`);render(d);R('redMessage').textContent='Assessment loaded from current-session evidence.'}catch(e){R('redMessage').textContent=e.message}}
function render(d){R('redHero').innerHTML=[['Target',d.target],['Flows',d.observed_flows||0],['Peers',d.peer_count||0],['Signals',d.security_signals||0],['Managed',d.managed_endpoint?'YES':'NO']].map(x=>`<div><div class="label">${esc(x[0])}</div><strong>${esc(x[1])}</strong></div>`).join('');R('redExposure').innerHTML=(d.exposures||[]).map(x=>`<div class="red-row"><b>${esc(x.port)} · ${esc(x.service_hint)}</b><br>${esc(x.flow_count)} observed flow(s)${x.administrative?' · administrative service':''}</div>`).join('')||'<div class="muted">No service exposure can be established from current telemetry.</div>';R('redHypotheses').innerHTML=(d.hypotheses||[]).map(x=>`<div class="red-row"><b>${esc(x.area)}</b><br>${esc(x.finding)}</div>`).join('');R('redPeers').innerHTML=(d.top_peers||[]).map(x=>`<div class="red-row"><b>${esc(x[0])}</b> · ${esc(x[1])} observed relationship(s)</div>`).join('')||'<div class="muted">No peers observed.</div>';R('redControls').innerHTML=(d.allowed_validation||[]).map(x=>`<div class="red-row">${esc(x)}</div>`).join('');R('redGuardrails').innerHTML=(d.guardrails||[]).map(x=>`<div class="red-row">${esc(x)}</div>`).join('')}
function tick(){inject();const b=document.querySelector('.tab[data-view="admin-red"]');if(b)b.style.display=token()?'block':'none'}tick();setInterval(tick,1200);
})();
</script>
"""
