SOC_UI_EXTENSION = r"""
<style>
.soc-grid{display:grid;grid-template-columns:1.1fr .9fr;gap:14px}.soc-card{border:1px solid #c7c7c7;padding:12px;min-width:0}.soc-list{max-height:420px;overflow:auto}.soc-row{border-bottom:1px solid #ddd;padding:8px 0;font:10px/1.45 Consolas,monospace;cursor:pointer}.soc-row:hover{background:#f3f3f3}.soc-row:last-child{border-bottom:0}.soc-hero{display:grid;grid-template-columns:repeat(4,1fr);border-left:1px solid #c7c7c7;border-top:1px solid #c7c7c7;margin:12px 0}.soc-hero>div{padding:10px;border-right:1px solid #c7c7c7;border-bottom:1px solid #c7c7c7}.soc-hero strong{display:block;font-size:17px;margin-top:4px}.soc-actions{display:flex;gap:7px;flex-wrap:wrap}.soc-pre{white-space:pre-wrap;word-break:break-word;font:10px/1.45 Consolas,monospace;max-height:360px;overflow:auto}.infra-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.infra-card{border:1px solid #c7c7c7;padding:12px;min-height:140px}.infra-scroll{max-height:300px;overflow:auto;margin-top:8px}@media(max-width:1000px){.soc-grid,.infra-grid{grid-template-columns:1fr}.soc-hero{grid-template-columns:1fr 1fr}}
</style>
<script>
(()=>{
const S=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function token(){return sessionStorage.getItem('campusOpsAdminToken')||''}
function headers(json=false){const h={};if(token())h['X-Campus-Admin']=token();if(json)h['Content-Type']='application/json';return h}
async function api(path,opt={}){const r=await fetch(path,{cache:'no-store',...opt,headers:{...headers(Boolean(opt.body)),...(opt.headers||{})}}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||`HTTP ${r.status}`);return d}
function inject(){if(!token()||S('view-admin-soc'))return;const nav=document.querySelector('nav'),main=document.querySelector('main'),foot=main?.querySelector('.foot');if(!nav||!main||typeof pages==='undefined')return;
  pages['admin-soc']=['SOC Desk','Cases, pivots and evidence workflow.'];pages['admin-infra']=['Infrastructure','Evidence-backed switch, port, VLAN and neighbor inventory.'];
  for(const [view,label] of [['admin-soc','SOC Desk'],['admin-infra','Infrastructure']]){const b=document.createElement('button');b.className='tab admin-tab show';b.dataset.view=view;b.textContent=label;b.onclick=()=>setView(view);nav.appendChild(b)}
  const soc=document.createElement('div');soc.className='view';soc.id='view-admin-soc';soc.innerHTML=`<section class="admin-shell"><div class="sectionhead"><div><h2>SOC Desk</h2><div class="small">Target pivot, case management, evidence and audit integrity.</div></div><div class="soc-actions"><button class="btn" id="socRefresh">Refresh</button><button class="btn" id="socVerify">Verify Audit</button></div></div><div class="admin-targetbar"><input id="socTarget" placeholder="Target IP / host / user"><button class="btn" id="socPivot">Pivot</button><button class="btn" id="socCreate">Create Case</button></div><div class="soc-hero" id="socHero"></div><div class="soc-grid"><div class="soc-card"><div class="label">Open Cases</div><div id="socCases" class="soc-list"></div></div><div class="soc-card"><div class="label">Selected Case</div><div id="socCaseDetail" class="small">Select a case.</div><div class="soc-actions" style="margin-top:10px"><button class="btn" data-status="INVESTIGATING">Investigating</button><button class="btn" data-status="CONTAINED">Contained</button><button class="btn" data-status="CLOSED">Close</button><button class="btn" id="socAttach">Export + Attach Evidence</button></div><textarea id="socNote" placeholder="Analyst note" style="width:100%;margin-top:10px;min-height:70px"></textarea><button class="btn" id="socAddNote" style="margin-top:7px">Add Note</button></div></div><div class="soc-card" style="margin-top:14px"><div class="label">Target Pivot</div><pre id="socPivotOut" class="soc-pre">Enter a target to pivot current-session evidence.</pre></div></section>`;main.insertBefore(soc,foot||null);
  const infra=document.createElement('div');infra.className='view';infra.id='view-admin-infra';infra.innerHTML=`<section class="admin-shell"><div class="sectionhead"><div><h2>Infrastructure Inventory</h2><div class="small">Only LLDP/CDP/SNMP/NAC/syslog evidence is promoted.</div></div><button class="btn" id="infraRefresh">Refresh</button></div><div class="infra-grid"><div class="infra-card"><div class="label">State</div><strong id="infraState">—</strong><div class="small" id="infraTruth"></div></div><div class="infra-card"><div class="label">Devices</div><strong id="infraDevices">0</strong><div class="infra-scroll" id="infraDeviceList"></div></div><div class="infra-card"><div class="label">VLAN Evidence</div><strong id="infraVlans">0</strong><div class="infra-scroll" id="infraVlanList"></div></div><div class="infra-card"><div class="label">Physical Links / Ports</div><strong id="infraLinks">0</strong><div class="infra-scroll" id="infraLinkList"></div></div></div></section>`;main.insertBefore(infra,foot||null);
  S('socRefresh').onclick=loadCases;S('socVerify').onclick=verifyAudit;S('socPivot').onclick=pivot;S('socCreate').onclick=createCase;S('socAttach').onclick=attachEvidence;S('socAddNote').onclick=addNote;document.querySelectorAll('#view-admin-soc [data-status]').forEach(b=>b.onclick=()=>updateCase(b.dataset.status));S('infraRefresh').onclick=loadInfra;loadCases();loadSocOverview();loadInfra();
}
let selectedCase=null;
async function loadSocOverview(){try{const d=await api('/api/v1/system/soc-overview'),sev=d.severity||{};S('socHero').innerHTML=[['Signals',d.signals||0],['High',sev.HIGH||0],['Critical',sev.CRITICAL||0],['Session',d.session_id||'—']].map(x=>`<div><div class="label">${esc(x[0])}</div><strong>${esc(x[1])}</strong></div>`).join('')}catch(e){if(S('socHero'))S('socHero').textContent=e.message}}
async function loadCases(){if(!S('socCases'))return;try{const d=await api('/api/v1/admin/cases'),rows=d.cases||[];S('socCases').innerHTML=rows.map(c=>`<div class="soc-row" data-case="${esc(c.case_id)}"><b>${esc(c.severity)} · ${esc(c.case_id)}</b><br>${esc(c.title)}<br>${esc(c.target)} · ${esc(c.status)}</div>`).join('')||'<div class="muted">No cases.</div>';S('socCases').querySelectorAll('[data-case]').forEach(el=>el.onclick=()=>selectCase(el.dataset.case));}catch(e){S('socCases').textContent=e.message}}
async function selectCase(id){try{selectedCase=await api('/api/v1/admin/cases/'+encodeURIComponent(id));renderCase()}catch(e){S('socCaseDetail').textContent=e.message}}
function renderCase(){const c=selectedCase;if(!c)return;S('socCaseDetail').innerHTML=`<b>${esc(c.case_id)}</b><br>${esc(c.title)}<br>Target: ${esc(c.target)}<br>Status: ${esc(c.status)} · Severity: ${esc(c.severity)}<br>Evidence: ${(c.evidence||[]).length} · Notes: ${(c.notes||[]).length}`;if(S('socTarget'))S('socTarget').value=c.target||''}
async function createCase(){const t=(S('socTarget').value||'').trim();if(!t)return;const title=prompt('Case title',`Investigation ${t}`);if(!title)return;try{selectedCase=await api('/api/v1/admin/cases',{method:'POST',body:JSON.stringify({title,target:t,severity:'MEDIUM'})});renderCase();await loadCases()}catch(e){alert(e.message)}}
async function updateCase(status){if(!selectedCase)return;try{selectedCase=await api('/api/v1/admin/cases/'+encodeURIComponent(selectedCase.case_id),{method:'PATCH',body:JSON.stringify({status})});renderCase();await loadCases()}catch(e){alert(e.message)}}
async function addNote(){if(!selectedCase)return;const note=(S('socNote').value||'').trim();if(!note)return;try{selectedCase=await api('/api/v1/admin/cases/'+encodeURIComponent(selectedCase.case_id),{method:'PATCH',body:JSON.stringify({note})});S('socNote').value='';renderCase();await loadCases()}catch(e){alert(e.message)}}
async function pivot(){const t=(S('socTarget').value||'').trim();if(!t)return;S('socPivotOut').textContent='Loading...';try{const d=await api('/api/v1/admin/soc/pivot/'+encodeURIComponent(t));S('socPivotOut').textContent=JSON.stringify(d,null,2)}catch(e){S('socPivotOut').textContent=e.message}}
async function attachEvidence(){if(!selectedCase)return;try{const e=await api('/api/v1/admin/evidence-export/'+encodeURIComponent(selectedCase.target),{method:'POST'});selectedCase=await api('/api/v1/admin/cases/'+encodeURIComponent(selectedCase.case_id)+'/evidence',{method:'POST',body:JSON.stringify({type:'EVIDENCE_BUNDLE',...e})});renderCase();await loadCases()}catch(err){alert(err.message)}}
async function verifyAudit(){try{const d=await api('/api/v1/admin/case-audit/verify');alert(`Audit ${d.state} · ${d.entries||0} entries`)}catch(e){alert(e.message)}}
async function loadInfra(){if(!S('infraState'))return;try{const d=await api('/api/v1/system/infrastructure-inventory');S('infraState').textContent=d.state||'UNKNOWN';S('infraTruth').textContent=d.truth_note||'';S('infraDevices').textContent=(d.devices||[]).length;S('infraVlans').textContent=(d.vlans||[]).length;S('infraLinks').textContent=(d.links||[]).length;S('infraDeviceList').innerHTML=(d.devices||[]).slice(0,50).map(x=>`<div class="soc-row"><b>${esc(x.name||x.id)}</b><br>${esc(x.description||'')}<br>${(x.interfaces||[]).length} interfaces</div>`).join('')||'<div class="muted">No infrastructure devices observed.</div>';S('infraVlanList').innerHTML=(d.vlans||[]).map(x=>`<div class="soc-row">VLAN ${esc(x.vlan)} · ${Number(x.observations||0)} observations</div>`).join('')||'<div class="muted">No VLAN evidence.</div>';S('infraLinkList').innerHTML=(d.links||[]).slice(0,80).map(x=>`<div class="soc-row">${esc(x.local||'?')} ${esc(x.local_port||'')} → ${esc(x.remote||'?')} ${esc(x.remote_port||'')}</div>`).join('')||'<div class="muted">No physical links observed.</div>'}catch(e){S('infraState').textContent='UNAVAILABLE';S('infraTruth').textContent=e.message}}
setInterval(inject,1200);setInterval(()=>{if(S('view-admin-soc')?.classList.contains('active')){loadSocOverview();loadCases()}if(S('view-admin-infra')?.classList.contains('active'))loadInfra()},8000);inject();
})();
</script>
"""
