TOOL_HUB_EXTENSION = r"""
<style>
#toolHubSection{margin-top:24px}.toolhub-summary{display:grid;grid-template-columns:repeat(4,1fr);border-left:1px solid #c7c7c7;border-top:1px solid #c7c7c7}.toolhub-summary>div{padding:12px;border-right:1px solid #c7c7c7;border-bottom:1px solid #c7c7c7}.toolhub-summary strong{display:block;font-size:20px;margin-top:5px}.toolhub-toolbar{display:flex;gap:7px;flex-wrap:wrap;margin:10px 0}.toolhub-toolbar input,.toolhub-toolbar select,.toolhub-discovery input,.toolhub-discovery select{height:32px;border:1px solid #aaa;background:#fff;padding:0 8px}.toolhub-grid{display:grid;grid-template-columns:repeat(3,minmax(220px,1fr));gap:10px}.toolhub-card{border:1px solid #bbb;padding:12px;min-height:135px}.toolhub-card strong{font-size:13px}.toolhub-state{float:right;border:1px solid #111;padding:2px 5px;font-size:8px;font-weight:800}.toolhub-meta{font-size:9px;color:#555;margin-top:7px;line-height:1.5}.toolhub-purpose{font-size:11px;line-height:1.45;margin-top:8px}.toolhub-protocols{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:10px}.toolhub-protocols>div{border:1px solid #bbb;padding:10px}.toolhub-help{border:1px solid #111;padding:12px;margin-top:12px;font-size:10px;line-height:1.55}.toolhub-discovery{border:2px solid #111;padding:14px;margin-top:16px}.toolhub-discovery-controls{display:grid;grid-template-columns:minmax(220px,1fr) 150px 190px;gap:8px;margin-top:10px}.toolhub-discovery-result{margin-top:12px;border:1px solid #bbb;padding:10px;max-height:280px;overflow:auto;font:10px/1.5 Consolas,monospace;white-space:pre-wrap}
@media(max-width:1000px){.toolhub-grid{grid-template-columns:1fr 1fr}.toolhub-summary,.toolhub-protocols{grid-template-columns:1fr 1fr}.toolhub-discovery-controls{grid-template-columns:1fr}}@media(max-width:650px){.toolhub-grid,.toolhub-summary,.toolhub-protocols{grid-template-columns:1fr}}
</style>
<script>
(()=>{
const $=id=>document.getElementById(id);let tools=[];
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function token(){return sessionStorage.getItem('campusOpsAdminToken')||''}
function install(){const system=$('view-system');if(!system||$('toolHubSection'))return;const s=document.createElement('section');s.id='toolHubSection';s.innerHTML=`<div class="sectionhead"><div><h2>Enterprise Tool Hub</h2><div class="small">Detected local/WSL tools and external telemetry adapters. Presence means capability readiness, not execution permission.</div></div><button class="btn" id="toolHubRefresh">Refresh</button></div><div class="toolhub-summary" id="toolHubSummary"></div><div class="toolhub-toolbar"><input id="toolHubSearch" placeholder="Find tool or purpose"><select id="toolHubPlane"><option value="">All planes</option></select><select id="toolHubState"><option value="">All states</option><option value="READY">Ready</option><option value="MISSING">Missing</option></select></div><div class="toolhub-grid" id="toolHubGrid"></div><div class="sectionhead" style="margin-top:18px"><h2>External Telemetry</h2></div><div class="toolhub-protocols" id="toolHubProtocols"></div><div class="toolhub-discovery"><div class="label">Authorized Discovery</div><div class="small">Admin-only active validation for a private/lab IPv4 host or CIDR. Host discovery is limited to 256 addresses per operator action.</div><div class="toolhub-discovery-controls"><input id="toolDiscoveryTarget" placeholder="10.20.80.0/24 or 10.20.80.25"><select id="toolDiscoveryMode"><option value="HOSTS">Host Discovery</option><option value="SERVICES">Service Verification</option></select><button class="btn" id="toolDiscoveryRun">Run Authorized Check</button></div><div class="toolhub-discovery-result" id="toolDiscoveryResult">No active discovery run.</div></div><div class="toolhub-help"><b>How to use this:</b> packet/flow/IDS tools feed monitoring; infrastructure tools establish real switch/router/VLAN evidence; endpoint/DFIR tools deepen host investigations; malware/detection tools validate files/events; discovery tools are active and must only be used against explicitly authorized private or lab targets. If a tool is missing, the console must degrade cleanly rather than fabricate its output.</div>`;system.appendChild(s);$('toolHubRefresh').onclick=load;$('toolHubSearch').oninput=render;$('toolHubPlane').onchange=render;$('toolHubState').onchange=render;$('toolDiscoveryRun').onclick=runDiscovery;load()}
async function runDiscovery(){const target=($('toolDiscoveryTarget').value||'').trim(),mode=$('toolDiscoveryMode').value,out=$('toolDiscoveryResult');if(!target){out.textContent='Enter a private lab target or CIDR.';return}if(!token()){out.textContent='Admin login is required before active discovery.';return}if(!confirm(`Run ${mode==='HOSTS'?'host discovery':'service verification'} against authorized private/lab target ${target}?`))return;out.textContent='Running authorized validation...';try{const r=await fetch('/api/v1/admin/discovery',{method:'POST',headers:{'Content-Type':'application/json','X-Campus-Admin':token()},body:JSON.stringify({target,mode,authorized:true})}),d=await r.json();if(!r.ok)throw new Error(d.detail||`HTTP ${r.status}`);out.textContent=JSON.stringify(d.result,null,2)}catch(e){out.textContent='Discovery failed: '+e.message}}
async function load(){try{const r=await fetch('/api/v1/system/telemetry-fabric',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error('HTTP '+r.status);tools=d.tools||[];renderSummary(d);renderProtocols(d.streaming_telemetry||{});populatePlanes();render()}catch(e){$('toolHubGrid').innerHTML=`<div class="toolhub-card">Tool fabric unavailable: ${esc(e.message)}</div>`}}
function renderSummary(d){const active=(tools||[]).filter(t=>String(t.state).startsWith('READY')).length,core=`${d.core_ready||0}/${d.core_total||0}`,missing=(tools||[]).length-active;$('toolHubSummary').innerHTML=[['Fabric',d.state||'UNKNOWN'],['Ready tools',active],['Missing optional',missing],['Core capture',core]].map(x=>`<div><div class="label">${esc(x[0])}</div><strong>${esc(x[1])}</strong></div>`).join('')}
function populatePlanes(){const select=$('toolHubPlane'),current=select.value,planes=[...new Set(tools.map(t=>t.plane).filter(Boolean))].sort();select.innerHTML='<option value="">All planes</option>'+planes.map(p=>`<option value="${esc(p)}">${esc(String(p).replaceAll('_',' '))}</option>`).join('');select.value=current}
function renderProtocols(p){$('toolHubProtocols').innerHTML=Object.entries(p).map(([k,v])=>`<div><div class="label">${esc(k.replaceAll('_',' '))}</div><strong>${esc(v.state||'UNKNOWN')}</strong><div class="small">${esc(v.model||'')} · ${esc(v.targets||0)} target(s)</div></div>`).join('')||'<div>No external telemetry configured.</div>'}
function render(){if(!$('toolHubGrid'))return;const q=($('toolHubSearch').value||'').toLowerCase(),plane=$('toolHubPlane').value,state=$('toolHubState').value;const rows=tools.filter(t=>{const ready=String(t.state).startsWith('READY');return(!q||`${t.name} ${t.purpose} ${t.plane}`.toLowerCase().includes(q))&&(!plane||t.plane===plane)&&(!state||(state==='READY'?ready:!ready))});$('toolHubGrid').innerHTML=rows.map(t=>`<div class="toolhub-card"><span class="toolhub-state">${esc(t.state)}</span><strong>${esc(t.name)}</strong><div class="toolhub-purpose">${esc(t.purpose)}</div><div class="toolhub-meta">PLANE ${esc(t.plane)}<br>MODE ${esc(t.mode||'PASSIVE')}<br>TIER ${esc(t.tier||'OPTIONAL')}<br>COMMAND ${esc(t.command||'—')}<br>${t.native_path?'NATIVE '+esc(t.native_path):t.wsl_path?'WSL '+esc(t.wsl_path):'NOT FOUND'}</div></div>`).join('')||'<div class="toolhub-card">No tools match this filter.</div>'}
setTimeout(install,700);setInterval(install,3000);
})();
</script>
"""
