TRAFFIC_EXTENSION = r"""
<style>
.traffic-live-grid{display:grid;grid-template-columns:repeat(6,1fr);border-left:1px solid #c7c7c7;border-top:1px solid #c7c7c7;margin-bottom:16px}
.traffic-live-cell{padding:12px;border-right:1px solid #c7c7c7;border-bottom:1px solid #c7c7c7;min-height:78px}
.traffic-live-cell b{display:block;font-size:18px;margin-top:7px}
.traffic-rank{display:grid;grid-template-columns:minmax(140px,1fr) 90px 90px 90px;padding:8px 0;border-bottom:1px solid #ddd;font-size:10px;gap:8px}
.traffic-rank strong{font-family:Consolas,Monaco,monospace}
.packet-pulse-row{display:grid;grid-template-columns:82px 90px 1fr 1fr 64px;gap:8px;padding:6px 8px;border-bottom:1px solid #ddd;font-size:10px}
.packet-pulse-row:last-child{border-bottom:0}
@media(max-width:1000px){.traffic-live-grid{grid-template-columns:repeat(3,1fr)}}
</style>
<script>
(()=>{
const Q=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const compactBits=v=>{v=Number(v||0);return v>=1e9?(v/1e9).toFixed(1)+' Gbps':v>=1e6?(v/1e6).toFixed(1)+' Mbps':v>=1e3?(v/1e3).toFixed(1)+' Kbps':v.toFixed(0)+' bps'};
const compactBytes=v=>{v=Number(v||0);return v>=1e9?(v/1e9).toFixed(1)+' GB':v>=1e6?(v/1e6).toFixed(1)+' MB':v>=1e3?(v/1e3).toFixed(1)+' KB':v+' B'};
const age=v=>{if(!v)return 1e9;const t=new Date(v).getTime();return Number.isFinite(t)?Math.max(0,(Date.now()-t)/1000):1e9};
function inject(){const view=Q('view-traffic');if(!view||Q('trafficDeep'))return;const section=document.createElement('section');section.id='trafficDeep';section.innerHTML='<div class="sectionhead"><h2>Live Traffic Analytics</h2></div><div class="traffic-live-grid" id="trafficDeepStats"></div><div class="equal"><div class="panel"><div class="label">Top Talkers</div><div id="trafficTalkers" style="margin-top:8px"></div></div><div class="panel"><div class="label">Recent Packet Pulse</div><div id="trafficPacketPulse" style="margin-top:8px;max-height:330px;overflow:auto"></div></div></div><div class="sectionhead" style="margin-top:18px"><h2>Rate-ranked Flows</h2></div><div class="tablewrap"><table><thead><tr><th>Source</th><th>Destination</th><th>Protocol</th><th>Application</th><th>PPS</th><th>Rate</th><th>Packets</th><th>Bytes</th><th>Age</th></tr></thead><tbody id="trafficRateRows"></tbody></table></div>';view.insertBefore(section,view.firstChild);}
function aggregate(flows){const map={};for(const f of flows){const key=f.src||'unknown';const row=map[key]??={src:key,pps:0,bps:0,bytes:0,dests:new Set(),protocols:new Set()};row.pps+=Number(f.pps_ewma||0);row.bps+=Number(f.bps_ewma||0);row.bytes+=Number(f.bytes||0);if(f.dst)row.dests.add(f.dst);if(f.protocol)row.protocols.add(f.protocol);}return Object.values(map).sort((a,b)=>b.bps-a.bps||b.bytes-a.bytes);}
function render(d){inject();const live=d?.live||{},flows=live.flows||[],packets=live.packet_feed||[],assets=live.assets||[];const totalBps=flows.reduce((s,f)=>s+Number(f.bps_ewma||0),0),totalPps=flows.reduce((s,f)=>s+Number(f.pps_ewma||0),0),recent=flows.filter(f=>age(f.first_seen)<15).length,publicPeers=assets.filter(a=>String(a.classification||a.role||'').includes('PUBLIC_PEER')).length,talkers=aggregate(flows),top=talkers[0];const stats=Q('trafficDeepStats');if(stats)stats.innerHTML=[['Active Flows',flows.length],['Packet Rate',totalPps.toFixed(1)+' pps'],['Observed Rate',compactBits(totalBps)],['New / 15s',recent],['Public Peers',publicPeers],['Top Source',top?.src||'—']].map(x=>`<div class="traffic-live-cell"><div class="label">${esc(x[0])}</div><b>${esc(x[1])}</b></div>`).join('');const tr=Q('trafficTalkers');if(tr)tr.innerHTML=talkers.slice(0,18).map(t=>`<div class="traffic-rank"><strong>${esc(t.src)}</strong><span>${compactBits(t.bps)}</span><span>${Number(t.pps).toFixed(1)} pps</span><span>${t.dests.size} peers</span></div>`).join('')||'<div class="muted">No traffic yet</div>';const pulse=Q('trafficPacketPulse');if(pulse)pulse.innerHTML=packets.slice(0,30).map(e=>{const p=e.payload||{};return `<div class="packet-pulse-row"><span>${esc(e.timestamp?new Date(e.timestamp).toLocaleTimeString():'—')}</span><span>${esc(p.protocol||p.transport||'—')}</span><span class="mono">${esc(p.src_ip||'—')}:${esc(p.src_port||'')}</span><span class="mono">${esc(p.dst_ip||'—')}:${esc(p.dst_port||'')}</span><span>${compactBytes(p.length||0)}</span></div>`}).join('')||'<div class="muted">No packets captured</div>';const rows=flows.slice().sort((a,b)=>Number(b.bps_ewma||b.packets||0)-Number(a.bps_ewma||a.packets||0)).slice(0,120),body=Q('trafficRateRows');if(body)body.innerHTML=rows.map(f=>`<tr><td class="mono">${esc(f.src)}:${esc(f.src_port||'')}</td><td class="mono">${esc(f.dst)}:${esc(f.dst_port||'')}</td><td>${esc(f.protocol||f.transport||'—')}</td><td>${esc(f.dns_query||f.tls_sni||f.http_host||'—')}</td><td>${Number(f.pps_ewma||0).toFixed(1)}</td><td>${compactBits(f.bps_ewma||0)}</td><td>${Number(f.packets||0).toLocaleString()}</td><td>${compactBytes(f.bytes||0)}</td><td>${age(f.last_seen)<1?'now':Math.round(age(f.last_seen))+'s'}</td></tr>`).join('')||'<tr><td colspan="9" class="muted">No active flows</td></tr>';}
inject();setInterval(()=>{try{render(snapshot)}catch{}},1000);
})();
</script>
"""
